/*================================================================================
pyoomph - a multi-physics finite element framework based on oomph-lib and GiNaC 
Copyright (C) 2021-2026  Christian Diddens, Duarte Rocha & Maxim de Wildt

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>. 

The main author may be contacted at c.diddens@utwente.nl

================================================================================*/


#pragma once
#include <vector>
#include <string>
#include "jitbridge.h"
#include <memory>

namespace pyoomph
{

  // Directory containing the headers/libraries needed to compile JIT-generated element
  // code (jitbridge.h and friends); set once at startup from the Python side.
  extern std::string g_jit_include_dir;

  // Base class for compiling the C code generated by codegen.cpp into a loadable shared
  // library (or, when TinyCC is available, directly into an in-memory relocated buffer),
  // and for resolving/loading the resulting JIT_ELEMENT_init entry point (see jitbridge.h).
  // The "To implement in C++"/"To implement in python" comments below mark which parts are
  // implemented directly here (TCC-based in-memory/DLL compilation, dlopen/LoadLibrary
  // loading) versus overridden by a Python-side subclass that shells out to a system C
  // compiler via distutils/setuptools (see CustomCCompiler and the Python bindings).
  class CCompiler
  {
  protected:
    std::string code_trunk; // File path (without extension) of the generated C source/shared library, when compiling via files
    std::string code;       // Generated C source held in memory, when compiling in-memory (see support_code_from_string)
    void *current_handle;   // Handle of the currently loaded shared library (or in-memory relocated code buffer)
    JIT_ELEMENT_init_SPEC init_in_mem; // Cached init function pointer when compiled directly into memory (TCC only)

  public:
    CCompiler();
    virtual std::string get_jit_include_dir() { return g_jit_include_dir; }
    virtual void set_code_from_string(const std::string &_code)
    {
      code = _code;
      code_trunk = "";
      current_handle = NULL;
    }
    virtual void set_code_from_file(const std::string &ftrunk)
    {
      code_trunk = ftrunk;
      code = "";
      current_handle = NULL;
    }
    virtual bool support_code_from_string() { return false; }
    virtual std::string get_code_trunk() { return code_trunk; }
    virtual void *get_current_handle() { return current_handle; }
    virtual void reset_current_handle() { current_handle = NULL; }

    virtual std::string get_shared_lib_extension(); // Platform-specific shared library suffix (.so/.dylib/.dll)

    // To implement in C++
    virtual std::string get_shared_library(std::string code_trunk) { return code_trunk + this->get_shared_lib_extension(); }
    virtual std::string expand_full_library_name(std::string relname) { return relname; }
    virtual void close_handle(void *handle); // Unload a previously loaded shared library handle (no-op for in-memory compilation)
    virtual JIT_ELEMENT_init_SPEC get_init_func(); // Compile-if-needed and return the JIT_ELEMENT_init entry point of the generated code

    // To implement in python
    virtual bool compile(bool suppress_compilation, bool suppress_code_writing, bool quiet, const std::vector<std::string> &extra_flags); // Compile `code`/the file at `code_trunk` into a shared library or in-memory buffer
    virtual bool sanity_check() { return false; }

    virtual bool compile_to_memory(); // Whether this compiler produces an in-memory relocated buffer (true, TCC) or an on-disk shared library (false)

    virtual ~CCompiler();
  };

  // Placeholder subclass used when compilation is fully delegated elsewhere (e.g. to a
  // Python-side compiler implementation that overrides compile()/compile_to_memory()
  // itself): both methods here are stubs that report "nothing compiled".
  class CustomCCompiler : public CCompiler
  {
  protected:
  public:
    virtual bool compile_to_memory() { return false; }
    virtual bool compile(bool , bool , bool , const std::vector<std::string> &) { return false; }
  };

}
