/*================================================================================
pyoomph - a multi-physics finite element framework based on oomph-lib and GiNaC 
Copyright (C) 2021-2026  Christian Diddens, Duarte Rocha & Maxim de Wildt

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>. 

The main author may be contacted at c.diddens@utwente.nl

================================================================================*/


#pragma once

#include "oomph_lib.hpp"

#include <vector>
#include <map>
#include <unordered_set>
#include <memory>
#include <tuple>
#include <typeinfo>

#include "jitbridge.h"
#include "mesh.hpp"

#include "hessian_tensor.hpp"

namespace pyoomph
{

  // class MeshTemplate;
  class Problem;
  class DynamicBulkElementInstance;
  class FiniteElementCode;
  class CCompiler;

  // Represents one compiled equation code, i.e. one shared library generated by the JIT code
  // generator (GiNaC symbolic equations -> C code -> compiled .so) for a single FiniteElementCode
  // (a bulk domain or an interface). A single DynamicBulkElementCode can be instantiated (via
  // factory_instance) on multiple meshes/domains, each giving a DynamicBulkElementInstance.
  class DynamicBulkElementCode
  {
  protected:
    friend class Problem;
    friend class DynamicBulkElementInstance;
    Problem *problem;
    CCompiler *compiler;
    std::string filename;
    JITFuncSpec_Table_FiniteElement_t *functable; // Function table exported by the compiled .so, containing all residual/jacobian/etc. callbacks
    FiniteElementCode *element_class; // The symbolic (GiNaC-based) code generator this binary was compiled from
    std::map<std::string, int> integral_function_map,extremum_function_map; // Name -> index lookup for integral/extremum diagnostic functions exposed by the code
    void *so_handle; // dlopen() handle of the loaded shared library

  public:
    const std::string &get_file_name() const { return filename; }
    DynamicBulkElementCode(Problem *prob, CCompiler *ccompiler, std::string fnam, FiniteElementCode *elem);
    virtual ~DynamicBulkElementCode(); // Closes the shared library handle
    // Creates a new instance of this code bound to a specific bulk mesh (fields, external data links, etc. are then resolved per-instance)
    DynamicBulkElementInstance *factory_instance(pyoomph::Mesh *bulkmesh);
    const JITFuncSpec_Table_FiniteElement_t *get_func_table() const { return functable; }
    JITFuncSpec_Table_FiniteElement_t *get_func_table() { return functable; }
    int get_max_dt_order() const { return get_func_table()->max_dt_order; }
    int get_integral_function_index(std::string n); // -1 if not present
    int get_extremum_function_index(std::string n); // -1 if not present
    unsigned _set_solved_residual(std::string name);
    FiniteElementCode *get_code() { return element_class; }
  };

  // enum FieldSpace {C1=1, C2=2};

  // A single link from an element to an "external" (i.e. not one of its own nodal/internal) Data object,
  // e.g. a coupling to a value living on another domain/mesh, or a global parameter exposed as Data.
  class ExternalDataLink
  {
  public:
    oomph::Data *data;   // External data object
    int value_index;     // Value of this external data to be taken
    int elemental_index; // Index of the external_data_pt inside the element
    ExternalDataLink(oomph::Data *d, int v) : data(d), value_index(v), elemental_index(-1) {}
  };

  // Collection of ExternalDataLinks for one DynamicBulkElementInstance, with deduplication of the
  // underlying Data pointers so that each distinct external Data object is only added once per element.
  class ExternalDataLinkVector : public std::vector<ExternalDataLink>
  {
  protected:
    std::vector<oomph::Data *> elemental_data; // Deduplicated list of Data objects that must be registered as external data on the element

  public:
    ExternalDataLinkVector(unsigned n) : std::vector<ExternalDataLink>(n, ExternalDataLink(NULL, -1)) {}
    void reindex_elemental_data(); // Rebuilds elemental_data from the (possibly sparsely filled) link entries, removing duplicates
    std::vector<oomph::Data *> &get_required_external_data() { return elemental_data; }
  };



  // A concrete instantiation of a DynamicBulkElementCode (one compiled .so) on a specific bulk mesh,
  // i.e. "load one .so -> instantiate for different fields (with different parameter sets)".
  // Multiple instances can share the same compiled code but bind to different meshes/field name mappings.
  class DynamicBulkElementInstance
  {
  protected:
    friend class DynamicBulkElementCode;
    friend class Problem;
    friend class FiniteElementCode;
    friend class BulkElementBase;
    DynamicBulkElementCode *dyn;
    DynamicBulkElementInstance(DynamicBulkElementCode *d, pyoomph::Mesh *bm);
    //  std::vector<int> local_field_to_global_field_index_C1;
    //  std::vector<int> local_field_to_global_field_index_C2;
    //  std::vector<int> local_global_parameter_to_global_index;
    ExternalDataLinkVector linked_external_data;
    pyoomph::Mesh *bulkmesh; // Bulk mesh -> required to identify interface field indices
  public:
    std::set<int> nullify_bulk_residuals; // indices to nullify bulk residual contributions of continuous spaces at interface, negative is position dof
    void link_external_data(std::string name, oomph::Data *data, int index,std::string full_source_name);
    Problem *get_problem() { return dyn->problem; }
    pyoomph::Mesh *get_bulk_mesh() { return bulkmesh; }
    std::map<std::string, unsigned> setup_interface_dof_indices(); // Populates the interface_dof_indices array in the space_info of the functable. This is required for continuous fields (C2TB-C1) to identify the additional dofs on interface nodes
    void set_bulk_mesh(pyoomph::Mesh *m) { bulkmesh = m; }
    FiniteElementCode *get_element_class() { return dyn->element_class; }
    void sanity_check(); // Consistency checks of the instance's field/external-data setup against the compiled function table; throws on failure
    DynamicBulkElementCode *get_code() { return dyn; }
    const DynamicBulkElementCode *get_code() const { return dyn; }
    bool has_parameter_contribution(const std::string  & param); // Whether the compiled code has a (residual/jacobian) contribution depending on the given global parameter
    /*void bind_field(const std::string & internal_name,const std::string & global_name);
    void bind_field(unsigned int index,std::string name,FieldSpace space);
    void bind_field_C1(unsigned int index,std::string name) {bind_field(index,name,L1);}
    void bind_field_C2(unsigned int index,std::string name) {bind_field(index,name,L2);}*/
    //  void bind_global_parameter(const std::string & internal_name, const std::string & global_name);
    // unsigned int get_num_fields_C1() const {return dyn->functable->numfields_C1;}
    //  int get_global_field_index_C1(const unsigned int & i) const {return local_field_to_global_field_index_C1[i];}
    // unsigned int get_num_fields_C2() const {return dyn->functable->numfields_C2;}
    bool can_be_time_adaptive() const { return dyn->functable->has_temporal_estimators; }
    //  int get_global_field_index_C2(const unsigned int & i) const {return local_field_to_global_field_index_C2[i];}
    unsigned int get_num_global_parameters() const { return dyn->functable->numglobal_params; }
    //  int get_global_parameter_index(const unsigned int & i) const {return local_global_parameter_to_global_index[i];}
    const JITFuncSpec_Table_FiniteElement_t *get_func_table() const { return dyn->get_func_table(); }
    JITFuncSpec_Table_FiniteElement_t *get_func_table() { return dyn->get_func_table(); }
    int get_max_dt_order() const { return dyn->get_max_dt_order(); }
    int get_nodal_field_index(std::string name);
    std::map<std::string, unsigned> get_nodal_field_indices();
    std::map<std::string, unsigned> get_elemental_field_indices();
    int get_discontinuous_field_index(std::string name);
    int get_integral_function_index(std::string n) { return dyn->get_integral_function_index(n); }
    int get_extremum_function_index(std::string n) { return dyn->get_extremum_function_index(n); }
    unsigned resolve_interface_dof_id(std::string n);
    std::string get_space_of_field(std::string name);
    bool has_moving_nodes() {return dyn->functable->moving_nodes;}
    ExternalDataLinkVector &get_linked_external_data() { return linked_external_data; }
  };

  class Problem;
  /*
  class FieldDescriptor
  {
   protected:
    std::string name;
    FieldSpace space;
    unsigned int global_index;
    Problem * problem;
   public:
    FieldDescriptor(Problem * p,const std::string & n, const FieldSpace & s, const unsigned int & gi) : name(n), space(s), global_index(gi), problem(p) {}
    const std::string & get_name() const {return name;}
    const FieldSpace & get_space() const {return space;}
    const unsigned int & get_global_index() const {return global_index;}
  };
  */

  // A single named global parameter (e.g. a scalar problem parameter used in the GiNaC equations
  // and exposed to Python via GiNaC_GlobalParam). Holds the actual double value and its global index
  // within the Problem's parameter list; the value itself is what oomph-lib's continuation/parameter
  // machinery takes a pointer to (via value()).
  class GlobalParameterDescriptor
  {
  protected:
    std::string name;
    unsigned int global_index;
    Problem *problem;
    double Value;
    bool positive=false; // If true, the parameter is restricted to non-negative values (enforced on write, e.g. from Python)
  public:
    GlobalParameterDescriptor(Problem *p, const std::string &n, const unsigned int &gi) : name(n), global_index(gi), problem(p), Value(0.0) {}
    const std::string &get_name() const { return name; }
    const unsigned int &get_global_index() const { return global_index; }
    double &value() { return Value; }
    const double &value() const { return Value; }
    void restrict_to_positive_values() {positive=true;}
    bool is_restricted_to_positive_values() const { return positive;}
    void set_analytic_derivative(bool active); // Toggle whether derivatives w.r.t. this parameter are obtained analytically (from the generated code) or by finite differences
    bool get_analytic_derivative();
    Problem *get_problem() { return problem; }
  };

  // Buffer used to pass a custom (user/Python-supplied) residual vector and Jacobian matrix (CSR) into
  // the assembly machinery, bypassing the normal elemental assembly. Used by Problem::get_custom_residuals_jacobian.
  class CustomResJacInformation
  {
   protected:
      friend class Problem;
      bool Require_jacobian; // Whether the caller actually needs the Jacobian (or just the residuals)
      std::string dparameter; // Name of the parameter w.r.t. which a derivative is requested, if any
      std::vector<double> residuals;
      oomph::Vector<double> Jvals;
      oomph::Vector<int> Jcolumn_index,Jrow_start;
   public:
      bool require_jacobian() const {return Require_jacobian;}
      void set_custom_residuals(const std::vector<double> & r) {residuals=r;}
      void set_custom_jacobian(const std::vector<double> & Jv, const std::vector<int> & col_index,const std::vector<int> & row_start);
      std::string get_parameter_name() const {return dparameter;}
      CustomResJacInformation(bool req_J,std::string parameter_name) : Require_jacobian(req_J), dparameter(parameter_name) {}
  };

  // Manages additional ("augmented") degrees of freedom that are appended to the normal dof vector,
  // e.g. extra scalar/vector unknowns and parameters introduced by constraints (arclength continuation,
  // phase conditions, etc). Vectors/scalars/parameters are registered via add_vector/add_scalar/add_parameter
  // before finalization, and split() can later decompose a full augmented dof vector back into its parts.
  class DofAugmentations
  {
    protected:
      friend class pyoomph::Problem;
      Problem * problem;
      std::vector<unsigned> types,split_offsets; // Per-entry type tag and offset (in the augmented dof block) used to reconstruct split()
      unsigned total_length; // Total number of augmented dofs added so far
      std::vector<std::vector<double>> augmented_vectors;
      std::vector<double> augmented_scalars;
      std::vector<std::string> augmented_parameters;
      bool finalized;
    public:
      DofAugmentations(Problem * _problem);
      unsigned add_vector(const std::vector<double> & v); // Registers a vector of augmented dofs, returns its offset
      unsigned add_scalar(const double & s); // Registers a single augmented scalar dof, returns its offset
      unsigned add_parameter(std::string); // Registers a global parameter as an augmented dof, returns its offset
      std::vector<std::vector<double>> split(unsigned startindex,int endindex); // Splits the augmented part of the dof vector back into the individually registered pieces

  };

  // Bookkeeping used when Dirichlet conditions are enforced by post-hoc matrix/residual manipulation
  // rather than by removing the corresponding dofs from the dof vector (see
  // Problem::dirichlets_by_removing_from_dof_vector). Tracks which (Data, index) pairs are pinned by
  // a Dirichlet condition and the corresponding set of global equation numbers.
  class DirichletMatrixManipulationInfo
  {
    protected:
      std::map<oomph::Data *,std::set<unsigned>> data_to_dirichlet_dof_indices;
      //std::map<unsigned long, double*> eqn_number_to_value_ptr;
      std::unordered_set<unsigned long> global_pinned_dof_set; // Global equation numbers that are Dirichlet-pinned, built by build_global_pinned_equation_set()
    public:
      void clear();
      void add_dirichlet_dof(oomph::Data *d, unsigned dof_index);
      //void build_equation_to_value_map();
      void build_global_pinned_equation_set(Problem *prob); // (Re)builds global_pinned_dof_set from data_to_dirichlet_dof_indices using the problem's current equation numbering
      const std::unordered_set<unsigned long> & get_global_pinned_equation_set() const {return global_pinned_dof_set;}
      //const std::map<unsigned long, double*> &get_eqn_number_to_value_map() const { return eqn_number_to_value_ptr; }

  };

  // The central orchestrator of a pyoomph simulation. Derives from oomph::Problem and adds:
  //  - management of the JIT-compiled equation codes (DynamicBulkElementCode/-Instance) and global parameters
  //  - the "defined field" bookkeeping used to detect empty Jacobian rows/columns (fields that must be pinned)
  //  - bifurcation/continuation tracking (fold, pitchfork, Hopf, azimuthal symmetry breaking, periodic orbits)
  //  - Hessian assembly for second-order (bifurcation/optimization) computations
  //  - custom sparse assembly, Dirichlet handling (either by dof removal or by matrix manipulation), logging
  // Most of the heavy lifting is implemented in problem.cpp; this header is the primary interface used both
  // from C++ (e.g. by generated element code, bifurcation.cpp) and from Python via src/nanobind/problem.cpp.
  // A frozen CSR sparsity pattern for ONE assembled matrix, together with the map that lets an
  // element's dense block be scattered straight into the value array by indexing, instead of being
  // accumulated into a searchable container and compressed afterwards. See
  // dev_docs/structural_assembly.md; this is what replaces the abandoned update_jacobian_csr_structure().
  //
  // Only meaningful while the pattern is value-independent (Problem::keep_structural_zeros), because
  // the whole point is that the same structure serves every assembly until the equations are
  // renumbered. `generation` records which Problem::get_jacobian_structure_id() it was built for.
  class FrozenSparsity
  {
  public:
    unsigned long generation = 0;   // Pattern id this was built for; 0 means "not built"
    unsigned matrix_index = 0;      // Which matrix of a multi-matrix assembly this describes
    unsigned long last_used = 0;    // LRU stamp, for choosing which entry to evict
    unsigned ndof = 0;
    unsigned long nelement = 0;
    std::vector<int> row_start;      // ndof+1, CSR row pointers
    std::vector<int> column_index;   // nnz, ascending within each row
    std::vector<int> element_offset; // nelement+1, where each element's entries start in the two arrays below
    // The scatter map, as a COMPACT list of the positions an element actually contributes to, rather
    // than a slot-or-(-1) entry for all nvar*nvar positions. Two parallel arrays: scatter_source is the
    // row-major offset i*nvar+j within the elemental block, scatter_slot the index in the value array.
    //
    // Sorted by scatter_slot within each element. That is the whole trick: the value array is far too
    // large to stay in cache, so scattered writes cost about a cache miss each, and walking an element's
    // contributions in increasing slot order turns them into a forward sweep that touches each cache
    // line once instead of revisiting it per row.
    std::vector<int> scatter_source;
    std::vector<int> scatter_slot;

    unsigned nnz() const { return row_start.empty() ? 0u : (unsigned)row_start.back(); }
    void clear()
    {
      generation = 0; matrix_index = 0; last_used = 0; ndof = 0; nelement = 0;
      row_start.clear(); column_index.clear(); element_offset.clear();
      scatter_source.clear(); scatter_slot.clear();
      row_start.shrink_to_fit(); column_index.shrink_to_fit(); element_offset.shrink_to_fit();
      scatter_source.shrink_to_fit(); scatter_slot.shrink_to_fit();
    }
  };

#ifdef OOMPH_HAS_MPI
  // The distributed counterpart of FrozenSparsity (Phase 2b of dev_docs/structural_assembly.md).
  //
  // oomph-lib's parallel_sparse_assemble() redoes, on every single assembly, work that only depends
  // on the equation numbering: which global rows this rank touches, which of them each other rank
  // owns, which column indices go with them, and -- the expensive part -- how the pieces arriving
  // from several ranks merge into one row. That merge is a linear rescan of the row built so far for
  // every incoming entry, i.e. quadratic in the row length, and it emits columns in first-seen order.
  // Measured on a 2D cavity at 2 ranks it was ~12.5 ms of the 19.9 ms of non-elemental time.
  //
  // Once the pattern is frozen every one of those is a constant, so this holds them:
  //
  //   * the local stage is a FrozenSparsity whose rows are my_eqns rather than 0..ndof-1;
  //   * the send plan is a set of CONTIGUOUS slices. my_eqns is sorted and the target distribution
  //     gives each rank a contiguous global range, so the rows destined for rank p are one run --
  //     which is the same property oomph's own first_eqn_element_for_proc relies on. Nothing has to
  //     be gathered before sending;
  //   * the merge becomes merge_perm: received value slot -> slot in the final value array. One
  //     scatter-add pass, no searching, no duplicate detection, no reallocation.
  //
  // Only values and residuals travel per assembly; the equation numbers, row lengths and column
  // indices go once, when the pattern is built. Unlike oomph's version the final column indices come
  // out sorted within each row, which is what the solvers want anyway.
  // The row/equation half of a distributed assembly plan: which global equations this rank
  // contributes to, how that set splits by owning rank, and which local row each incoming equation
  // lands on. It depends on the equation numbering and the mesh partition alone -- not on any matrix,
  // not on the symbolic mask, not even on keep_structural_zeros -- which is why the residual-only
  // assembly can use it when nothing else about the frozen machinery applies.
  //
  // Held separately from the matrix plan rather than shared with it. During get_residuals() oomph-lib
  // installs a ParallelResidualsHandler, which reports a different assembly-handler type and hence a
  // different pattern id, so one slot would be evicted and rebuilt on every single Newton step -- the
  // same thrashing that §A5 had to fix for the serial cache.
  class DistributedResidualPlan
  {
  public:
    unsigned long generation = 0; // 0 means "not built"
    unsigned nproc = 0, my_rank = 0;
    unsigned nrow_local = 0, first_row = 0;
    unsigned long nelement = 0;
    unsigned ndof = 0;
    unsigned n_vector = 0;
    std::vector<unsigned> my_eqns;   // sorted global equations this rank contributes to
    std::vector<int> send_row_start; // nproc+1; rows for rank p are my_eqns[send_row_start[p]..[p+1])
    std::vector<int> recv_eq_start;  // nproc+1 into recv_eq_row
    std::vector<int> recv_eq_row;    // local row (global - first_row) of each equation arriving
    // Elemental dof -> row in my_eqns, precomputed. Without it every scatter bisects my_eqns once per
    // dof, which is the bulk of what is left of a residual-only assembly once the exchange is frozen.
    std::vector<int> res_element_offset; // nelement+1
    std::vector<int> res_slot;           // row in my_eqns, one per contributing elemental dof
    void clear()
    {
      generation = 0; nproc = my_rank = 0; nrow_local = first_row = 0; nelement = 0; ndof = 0;
      n_vector = 0;
      my_eqns.clear(); send_row_start.clear(); recv_eq_start.clear(); recv_eq_row.clear();
      res_element_offset.clear(); res_slot.clear();
    }
  };

  class DistributedFrozenSparsity
  {
  public:
    // One matrix's worth of pattern. The row/equation plan below is shared by all of them.
    class Mat
    {
    public:
      // Local stage: CSR over my_eqns rows, global column indices, sorted within a row.
      std::vector<int> local_row_start;  // my_eqns.size()+1
      std::vector<int> local_col;        // local nnz
      std::vector<int> element_offset;   // nelement+1
      std::vector<int> scatter_source;   // i*nvar+j within the elemental block
      std::vector<int> scatter_slot;     // slot in the local value array; sorted per element, as in FrozenSparsity
      // Send plan: values for rank p are local_values[send_nz_start[p] .. send_nz_start[p+1]).
      std::vector<int> send_nz_start;    // nproc+1
      // Merge plan: the block received from rank p occupies merge_perm[recv_nz_start[p] .. [p+1]),
      // and entry k of it adds into final_values[merge_perm[recv_nz_start[p]+k]].
      std::vector<int> recv_nz_start;    // nproc+1
      std::vector<int> merge_perm;
      // The answer.
      std::vector<int> final_row_start;  // nrow_local+1
      std::vector<int> final_col;        // final nnz
    };

    unsigned long generation = 0; // Pattern id this was built for; 0 means "not built"
    unsigned long last_used = 0;
    unsigned nproc = 0, my_rank = 0;
    unsigned ndof = 0;                  // global
    unsigned nrow_local = 0, first_row = 0;
    unsigned long nelement = 0;
    unsigned n_matrix = 0, n_vector = 0;
    std::vector<unsigned> my_eqns;      // sorted global equations this rank contributes to
    // Rows destined for rank p are my_eqns[send_row_start[p] .. send_row_start[p+1]).
    std::vector<int> send_row_start;    // nproc+1
    // Equations arriving from rank p are recv_eq_row[recv_eq_start[p] .. [p+1]), already converted
    // to a local row index (global row - first_row).
    std::vector<int> recv_eq_start;     // nproc+1
    std::vector<int> recv_eq_row;
    std::vector<Mat> mats;

    void clear()
    {
      generation = 0; nproc = my_rank = 0; ndof = 0; nrow_local = first_row = 0;
      nelement = 0; n_matrix = n_vector = 0;
      my_eqns.clear(); send_row_start.clear(); recv_eq_start.clear(); recv_eq_row.clear();
      mats.clear();
    }
  };
#endif

  class Problem : public oomph::Problem
  {
  protected:
    CCompiler *compiler; // C compiler front-end used to compile the JIT-generated equation code into shared libraries
    std::ofstream * logfile;
    bool _is_quiet;
    friend class DynamicBulkElementInstance;
    //	 MeshTemplate *meshtemplate;
    std::vector<DynamicBulkElementCode *> bulk_element_codes; // All compiled equation codes loaded so far (owned by the Problem)
    //   std::map<std::string,FieldDescriptor*> fields_by_name;
    //   std::vector<FieldDescriptor*> fields_by_index;
    std::map<std::string, GlobalParameterDescriptor *> global_params_by_name;
    std::vector<GlobalParameterDescriptor *> global_params_by_index; // Indexed by GlobalParameterDescriptor::get_global_index()
    //   const FieldDescriptor * assert_field(const std::string & name,const FieldSpace & space );

    oomph::CRDoubleMatrix *eigen_JacobianMatrixPt, *eigen_MassMatrixPt; // Cached Jacobian/mass matrices from the last assemble_eigenproblem_matrices() call
    double global_temporal_error_norm() override; // Combines the per-mesh temporal error norm contributions into a single global error estimate used for adaptive timestepping
    std::string bifurcation_tracking_mode = ""; // "", "fold", "pitchfork", "hopf", "azimuthal", ... - empty means no bifurcation tracking is active
    std::string _solved_residual = ""; // Name of the currently active residual (multi-residual problems can switch which residual/Jacobian assign_eqn_numbers/get_jacobian operate on); "" means the default combined residual
    bool symmetric_hessian_assembly=true; // Whether the Hessian tensor assembly exploits the symmetry of the second derivative (faster, but requires the underlying form to actually be symmetric)
    // If true, we do it the oomph-lib way (remove dofs of Dirichlet). If false, all Dirichlets are kept as dofs and the system is manipulated afterwards
    // (note: completely pinned fields without any weak formulation (usually helper field, e.g. references for normalized arclength etc) are always removed from the dofs, independent of this setting)
    bool dirichlets_by_removing_from_dof_vector=true;

    // ON by default. It was opt-in while the pattern was the full element-connectivity one (which cost
    // up to +35% nonzeros on weakly coupled multi-physics); pruning it by the code generator's field
    // coupling made it free (<= +0.2% nonzeros, within noise on time), and it is what lets the linear
    // solvers skip their symbolic phase - about -20% per Newton solve.
    bool keep_structural_zeros=true; // See set_keep_structural_zeros()
    bool keep_structural_zeros_in_secondary_matrices=false; // Same, but for the mass matrix / other non-primary matrices of a multi-matrix assembly
    bool prune_structural_zeros_by_field_coupling=true; // Use the codegen field-coupling tables to keep the structural pattern tight (see the setter)
    // Whether an explicit diagonal is needed is a property of the LINEAR SOLVER, not of the problem:
    // only some PETSc factorisations require one, MUMPS does not, and the stored zeros are not free --
    // they change the matrix a direct solver sees, hence its pivoting, hence the solution at round-off
    // level (see dev_docs/structural_assembly.md). So this is a tri-state: by default the problem asks
    // the active solver (solver_requires_explicit_diagonal, pushed down from Python before each solve),
    // and setting the flag explicitly overrides that answer in either direction.
    bool force_jacobian_diagonal_entries=false;      // The override value; only consulted when not auto
    bool force_jacobian_diagonal_entries_auto=true;  // Cleared by set_force_jacobian_diagonal_entries()
    bool solver_requires_explicit_diagonal=false;    // What the active linear solver last reported
    bool diagonal_entries_are_forced() const { return force_jacobian_diagonal_entries_auto ? solver_requires_explicit_diagonal : force_jacobian_diagonal_entries; }
    // One scratch buffer PER MATRIX INDEX, not one shared buffer: a multi-matrix assembly fetches the
    // masks for all matrices of an element before using any of them, so the pointers handed out for
    // different matrix_index must stay valid simultaneously. Sharing one buffer silently aliased the
    // Jacobian's mask onto the mass matrix's.
    std::vector<std::vector<char>> sparsity_mask_scratch;

    bool verify_frozen_sparsity=true; // Check per element that nothing nonzero fell outside the frozen pattern
    bool use_frozen_sparsity=true; // Assemble straight into a preallocated CSR when the pattern allows it (see assemble_with_frozen_sparsity)
    // Section 7e: let a bifurcation-tracking assembly handler describe its AUGMENTED elemental block
    // (see AugmentedBlockSpec) so the frozen path can apply to it too -- it otherwise cannot, the block
    // being several times larger than the element's own field description. Only handlers that provide a
    // description are affected; the rest fall back exactly as before. Measured -22% on a full PDE fold
    // tracking solve and -31% per re-solve, same fold point to 12 digits.
    bool use_frozen_sparsity_for_bifurcation_tracking=true;
    // Several frozen patterns are kept at once, keyed by (pattern id, matrix index). A single slot per
    // matrix index is not enough: a workflow that alternates between two DIFFERENT patterns -- most
    // obviously a PETSc preconditioner matrix assembled from another residual via
    // PETSCSolver.assemble_matrix, but also any multi-residual problem -- would evict and rebuild on
    // every assembly, and a rebuild is two passes over the mesh plus a sort. That is strictly worse
    // than not caching at all, so the cache has to hold more than one.
    std::vector<FrozenSparsity> frozen_sparsity_cache;
    unsigned frozen_sparsity_cache_capacity = 8; // Raised on the fly if a single assembly needs more
    unsigned long frozen_sparsity_clock = 0;     // Monotonic source for the LRU stamps
    unsigned long frozen_sparsity_rebuilds = 0;  // How many patterns have been built; a test can watch this for thrashing
    // How many matrix slots the frozen patterns reserved, summed over every frozen assembly, and how
    // many of those ended up holding exactly zero. A frozen pattern is deliberately a SUPERSET of the
    // numerically nonzero entries -- it has to be, or it would not be reusable -- so the ratio is the
    // price of freezing: extra stored zeros the solver still has to carry. Cheap to keep (one pass
    // over the values already in cache at the end of an assembly) and the only way to tell a tight
    // pattern from a wasteful one without dumping matrices.
    unsigned long long frozen_sparsity_stored_entries = 0;
    unsigned long long frozen_sparsity_zero_entries = 0;
    // Index into frozen_sparsity_cache of a usable pattern for (matrix_index, generation), building it
    // if necessary. `pinned` lists slots the current assembly is already using, which must not be
    // evicted. Returns -1 if the pattern cannot be built (see build_frozen_sparsity).
    int acquire_frozen_sparsity(unsigned matrix_index, unsigned long generation, unsigned ndof, const std::vector<int> &pinned, unsigned mask_matrix_index_override=(unsigned)-1);
    // Builds the frozen pattern and scatter map for matrix matrix_index. Returns false if this problem
    // cannot be described that way (any element without a symbolic mask), leaving sp cleared.
    // `nd_override` is the row/column count to build for, or 0 for this->ndof(). The base-problem
    // assembly needs the UNAUGMENTED count, which differs from ndof() while an augmentation is active.
    bool build_frozen_sparsity(unsigned mask_matrix_index, FrozenSparsity &sp, unsigned nd_override=0);
    // Sentinel mask index: not a matrix, but "the union of the Jacobian and mass-matrix masks together
    // with their TRANSPOSES". Needed by the multi-assembly, which builds transposed Hessian-vector
    // products (bifurcation tracking on a LEFT eigenvector) whose pattern is J^T, not J.
    static constexpr unsigned MASK_UNION_SYMMETRIC = (unsigned)-3;
    // Sentinel matrix index selecting the HESSIAN coupling table rather than the Jacobian or mass one.
    static constexpr unsigned MASK_HESSIAN = (unsigned)-5;
    // Likewise for the MASS-MATRIX coupling table. Distinct from matrix index 1, which additionally
    // means "the second matrix of a multi-matrix assembly" and is only meaningful under an
    // EigenProblemHandler; this one only selects the table, which is meaningful whatever is assembling.
    static constexpr unsigned MASK_MASS = (unsigned)-6;
    std::vector<char> union_mask_scratch;
    // Whether the multi-assembly currently being built asks for a TRANSPOSED product, whose pattern is
    // J^T rather than J. Set from the request list; true by default so that any other caller of the
    // base-problem assembly gets the safe superset rather than a refusal.
    bool multiassembly_wants_transposed = true;
    const char *symmetrised_union_mask(oomph::GeneralisedElement *elem_pt, unsigned nvar);
    // The fast assembly path: fills the output arrays directly from the frozen pattern. Returns false
    // without touching them if the pattern route does not apply, so the caller falls back to oomph-lib.
    bool assemble_with_frozen_sparsity(oomph::Vector<int*>& column_or_row_index, oomph::Vector<int*>& row_or_column_start, oomph::Vector<double*>& value, oomph::Vector<unsigned>& nnz, oomph::Vector<double*>& residuals, bool compressed_row_flag);
#ifdef OOMPH_HAS_MPI
    // Phase 2b. Substitutes the frozen distributed assembly for oomph-lib's whenever the pattern is
    // known, and calls oomph-lib's otherwise -- so this is always revertible at runtime, and any
    // configuration the freezing does not cover simply keeps the old behaviour.
    void parallel_sparse_assemble(const oomph::LinearAlgebraDistribution* const& dist_pt, oomph::Vector<int*>& column_or_row_index, oomph::Vector<int*>& row_or_column_start, oomph::Vector<double*>& value, oomph::Vector<unsigned>& nnz, oomph::Vector<double*>& residuals) override;
    DistributedFrozenSparsity distributed_frozen_sparsity;
    unsigned long distributed_frozen_rebuilds = 0;
    bool use_frozen_distributed_sparsity = true; // Freeze the distributed pattern and exchange values only
    // Builds the whole distributed plan -- local pattern, send slices, and the merge permutation
    // derived from one round of pattern exchange. False (leaving sp cleared) if this configuration
    // cannot be frozen, in which case the caller falls back to oomph-lib.
    bool build_distributed_frozen_sparsity(const oomph::LinearAlgebraDistribution* const& dist_pt, unsigned n_matrix, unsigned n_vector, DistributedFrozenSparsity &sp);
    // The row/equation half, shared by the matrix and the residual-only plans so there is one
    // implementation of it. COLLECTIVE: it exchanges the equation numbers. Returns false, identically
    // on every rank, if the configuration cannot be planned.
    bool build_distributed_residual_plan(const oomph::LinearAlgebraDistribution* const& dist_pt, unsigned n_vector, DistributedResidualPlan &rp);
    DistributedResidualPlan distributed_residual_plan;
    unsigned long distributed_residual_rebuilds = 0;
    // The residual-only distributed fast path. oomph-lib routes get_residuals() under MPI through the
    // whole of parallel_sparse_assemble() with zero matrices: it recomputes my_eqns, builds the
    // array-of-arrays, exchanges equation numbers and merges by bisection per row -- all to sum a
    // vector. Measured at 45 % of a residual assembly at 4 ranks, and roughly constant as ranks grow.
    bool assemble_distributed_residuals_only(const oomph::LinearAlgebraDistribution* const& dist_pt, oomph::Vector<double*>& residuals);
    // The fast distributed path. False, having touched nothing, if the frozen route does not apply.
    bool assemble_distributed_with_frozen_sparsity(const oomph::LinearAlgebraDistribution* const& dist_pt, oomph::Vector<int*>& column_or_row_index, oomph::Vector<int*>& row_or_column_start, oomph::Vector<double*>& value, oomph::Vector<unsigned>& nnz, oomph::Vector<double*>& residuals);
#endif
    // Everything besides the equation numbering that the sparsity pattern depends on. The id is a
    // FUNCTION of this state, not a counter: returning to a configuration seen before must yield the id
    // it had before, or nothing downstream can ever hit its cache. A workflow that alternates between
    // the Newton assembly and the eigenproblem assembly (which installs its own assembly handler) does
    // exactly that on every step, and with a counter it re-derived the pattern every single time.
    // Ids are never recycled: invalidation clears the map but the counter keeps climbing, so an id held
    // by a solver from before a renumbering can never accidentally match afterwards.
    // Keyed on the assembly handler's TYPE, not its address: the eigenproblem assembly news and deletes
    // its handler on every call, so the address varies and an address key would miss every time.
    typedef std::tuple<std::string, unsigned long, unsigned, std::string> JacobianStructureKey; // handler type, ndof, n_unaugmented, active residual
    std::map<JacobianStructureKey, unsigned long> jacobian_structure_ids;
    unsigned long next_jacobian_structure_id = 0;

    void actions_after_change_in_global_parameter(double *const &parameter_pt) override; // oomph-lib hook: resolves parameter_pt to its name and forwards to the string-named overload below
    void actions_after_parameter_increase(double *const &parameter_pt) override;

    double lambda_tracking_real = 0.0; // Real(lambda) for tracking of eigenbranches
    virtual void sparse_assemble_row_or_column_compressed_for_periodic_orbit(oomph::Vector<int*>& column_or_row_index,oomph::Vector<int*>& row_or_column_start,oomph::Vector<double*>& value,oomph::Vector<unsigned>& nnz,oomph::Vector<double*>& residuals,bool compressed_row_flag); // Specialized sparse assembly for the augmented system used during periodic orbit tracking
    void sparse_assemble_row_or_column_compressed(oomph::Vector<int*>& column_or_row_index,oomph::Vector<int*>& row_or_column_start,oomph::Vector<double*>& value,oomph::Vector<unsigned>& nnz,oomph::Vector<double*>& residual,bool compressed_row_flag) override; // Dispatches to the base-problem or periodic-orbit assembly depending on the active assembly handler
    unsigned n_unaugmented_dofs=0; // Number of dofs of the "physical" problem, i.e. excluding any bifurcation-tracking/arclength augmentation dofs
    std::vector<std::string> defined_fields; // All globally known field names (across all domains), used for the empty-Jacobian-row/col analysis
    std::vector<DynamicBulkElementCode*> defined_fields_to_domain; // Parallel to defined_fields: the code (domain) each field was defined in
    std::vector<std::string> residual_names; // Names of all residuals defined in the problem (for multi-residual/multi-assembly problems)
    std::vector<std::vector<bool>> residual_contributing_fields; // [residual][defined_field] -> whether the defined field contributes to the residual (i.e. whether there is a least a test function contributing to it)
    std::vector<std::vector<std::vector<bool>>> jacobian_contributing_fields; // [residual][defined_field][defined_field] -> whether the jacobian has a contribution from the derivative of the residual w.r.t. the defined field (i.e. whether there is at least a test function and trial function contributing to it)
    std::vector<std::vector<std::set<DynamicBulkElementCode*>>> residual_contributing_codes; // [residual][defined_field] -> Contributions to the residual from the different codes (e.g. bulk, interface, different domains)
    std::vector<std::vector<std::vector<std::set<DynamicBulkElementCode*>>>> jacobian_contributing_codes; // [residual][defined_field][defined_field] -> Contributions to the jacobian from the different codes (e.g. bulk, interface, different domains)
    std::vector<std::vector<bool>> pin_due_to_empty_jacobian_row_or_col; // [residual][defined_field] -> whether this field has to be pinned due to an empty jacobian row (i.e. no contributions on the current residual which leads to a non-invertible jacobian)
    std::vector<bool> removed_fields_due_to_missing_jacobian_row_or_col; // [defined_field] -> whether this field has been removed from the dofs due to missing jacobian row (i.e. no contributions on any residual, which leads to a non-invertible jacobian)
    std::vector<std::map<unsigned,unsigned>> global_eqs_to_jacobian_buffer_index; // [global col][global row]->[index in the jacobian buffer]

    DirichletMatrixManipulationInfo dirichlet_info;  // only used if not dirichlets_by_removing_from_dof_vector
  public:

    bool are_Dirichlets_by_removing_from_dof_vector() const { return dirichlets_by_removing_from_dof_vector; }
    // Switches between the two Dirichlet-enforcement strategies (see dirichlets_by_removing_from_dof_vector); no-op if unchanged
    void set_Dirichlets_by_removing_from_dof_vector(bool v) {
      if (v==dirichlets_by_removing_from_dof_vector) return; // No change
      // TODO: Check here whether the problem is already initialized and throw an error if this is the case, since changing this after initialization would require a reinitialization of the problem
      dirichlets_by_removing_from_dof_vector=v;
    }
    void assemble_defined_field_list(); // (Re)builds defined_fields/defined_fields_to_domain and the residual/jacobian-contribution tables from all currently loaded bulk element codes
    void update_jacobian_csr_structure(); // Rebuilds global_eqs_to_jacobian_buffer_index after the equation numbering or sparsity pattern has changed
    std::tuple<std::string,bool> get_jacobian_information_string(); // Human-readable report of which fields/residuals contribute to the Jacobian (and whether any dofs had to be pinned due to empty rows/cols), for debugging singular Jacobians
    void sparse_assemble_row_or_column_compressed_base_problem(oomph::Vector<int*>& column_or_row_index,oomph::Vector<int*>& row_or_column_start,oomph::Vector<double*>& value,oomph::Vector<unsigned>& nnz,oomph::Vector<double*>& residuals,bool compressed_row_flag); // The "normal" (non-periodic-orbit) sparse assembly, used as fallback by sparse_assemble_row_or_column_compressed()
    unsigned get_n_unaugmented_dofs() const {return n_unaugmented_dofs;}
    bool use_custom_residual_jacobian=false; // If true, residuals/Jacobian are supplied by get_custom_residuals_jacobian() instead of elemental assembly
    bool improved_pitchfork_tracking_on_unstructured_meshes=false;
    bool is_field_removed_from_dofs_due_to_missing_jacobian_row(int global_field_index);

    double * get_lambda_tracking_real() {return &lambda_tracking_real;}

    void set_sparse_assembly_method(const std::string & method); // Selects the sparse assembly implementation (oomph-lib's built-in variants, e.g. "default","single_thread","openmp_...")
    std::string get_sparse_assembly_method();

    // --- Structural (value-independent) sparsity, see dev_docs/structural_assembly.md ---
    // By default, oomph-lib drops any Jacobian entry that evaluates to exactly zero, which makes the
    // emitted CSR pattern depend on the current dof values: it can (and does) change from one Newton
    // step to the next. Keeping structural zeros makes the pattern depend on the equation numbering
    // alone, so it is stable until the next assign_eqn_numbers() - which is what lets linear solvers
    // reuse their symbolic phase (Pardiso phase 11, a PETSc Mat's preallocation) across solves. It
    // also guarantees an entry on every diagonal, since every dof sits in an element whose block
    // contains (i,i) - replacing the manual MatShift(0.0) some PETSc backends need.
    // Applies to the Jacobian / main matrix only; the mass matrix keeps its own, much tighter pattern
    // (see numerical_zero_for_sparse_assembly() in the .cpp).
    void set_keep_structural_zeros(bool yesno);
    bool get_keep_structural_zeros() const { return keep_structural_zeros; }
    // Opt in to structural zeros for the secondary matrices of a multi-matrix assembly too (the mass
    // matrix of the eigenproblem assembly). Off by default, and usually should stay off.
    void set_keep_structural_zeros_in_secondary_matrices(bool yesno);
    bool get_keep_structural_zeros_in_secondary_matrices() const { return keep_structural_zeros_in_secondary_matrices; }
    // Per-matrix "treat as zero and do not store" threshold used by every sparse assembly routine.
    double numerical_zero_for_sparse_assembly(const unsigned &matrix_index) const override;
    // Per-element structural sparsity mask, built from the code generator's symbolic field-coupling
    // tables. See the base declaration in oomph-lib's problem.h and dev_docs/structural_assembly.md.
    const char *sparsity_mask_for_element(const unsigned &matrix_index, oomph::GeneralisedElement *const &elem_pt, const unsigned &nvar) override;
    // Tiles an AUGMENTED elemental block's mask from the raw ones, using the description the assembly
    // handler provides (see AugmentedBlockSpec). NULL if it cannot be described, so the caller falls back.
    const char *augmented_sparsity_mask_for_element(const unsigned &matrix_index, oomph::GeneralisedElement *const &elem_pt, const unsigned &nvar, unsigned raw_nvar);
    // The core of both: fills `out` with the field-coupling mask of one (matrix, residual) pair.
    // `residual_override` < 0 means "the residual the element is currently assembling"; anything else
    // names a specific one, which is what a tracker mixing several residuals in one augmented block
    // needs (azimuthal: base + real + imaginary azimuthal; pitchfork: base + mass-matrix residual).
    bool field_coupling_mask_for_element(unsigned matrix_index, int residual_override, oomph::GeneralisedElement *const &elem_pt, const unsigned &nvar, std::vector<char> &out);
    // Raw masks for the augmented tiling, one per (matrix, residual) pair needed by the spec. Kept as a
    // member so the buffers survive between elements; indices into it stay stable for one call because
    // the whole set of keys is collected before any of them is filled.
    struct AugmentedRawMask { unsigned matrix = 0; int residual = -1; std::vector<char> data; };
    std::vector<AugmentedRawMask> augmented_raw_masks;
    // Whether the value-independent pattern is pruned to the field pairs the code generator proves can
    // contribute (tight, "Tier B"), or is the full element-connectivity pattern ("Tier A"). Pruning is
    // strictly better where it applies -- it reproduced the numerical pattern exactly on every problem
    // measured, against up to 1.37x for connectivity -- so it is on by default.
    void set_prune_structural_zeros_by_field_coupling(bool yesno);
    bool get_prune_structural_zeros_by_field_coupling() const { return prune_structural_zeros_by_field_coupling; }
    // Whether every diagonal entry is forced into the pattern even where no field pair contributes to
    // it. Off by default: only some PETSc factorisations require it (MUMPS does not), and the stored
    // zeros perturb a direct solver's pivoting. Turn it on for a solver that needs it -- with pruning
    // on, Taylor-Hood's pressure-pressure diagonal is exactly such a case.
    void set_force_jacobian_diagonal_entries(bool yesno); // Explicit override; disables the automatic answer
    bool get_force_jacobian_diagonal_entries() const { return diagonal_entries_are_forced(); } // The EFFECTIVE value
    void set_force_jacobian_diagonal_entries_auto(); // Go back to asking the solver
    bool get_force_jacobian_diagonal_entries_is_auto() const { return force_jacobian_diagonal_entries_auto; }
    // Pushed down from the Python solver layer before assembling; only consulted in auto mode.
    void set_solver_requires_explicit_diagonal(bool yesno);
    bool get_solver_requires_explicit_diagonal() const { return solver_requires_explicit_diagonal; }
    // Whether assembly may write straight into a preallocated CSR using a precomputed scatter map,
    // skipping the accumulate-into-a-container-then-compress work entirely. Requires a value-independent
    // pattern; falls back to oomph-lib's assembly automatically whenever it cannot apply (distributed
    // runs, augmented systems, compressed-column output, any element without a symbolic mask).
    void set_use_frozen_sparsity(bool yesno);
    bool get_use_frozen_sparsity() const { return use_frozen_sparsity; }
    void set_use_frozen_sparsity_for_bifurcation_tracking(bool yesno) { use_frozen_sparsity_for_bifurcation_tracking = yesno; invalidate_jacobian_structure(); }
    bool get_use_frozen_sparsity_for_bifurcation_tracking() const { return use_frozen_sparsity_for_bifurcation_tracking; }
    // Whether each element's block is checked against the frozen pattern during assembly (see the
    // assembly loop). Cheap relative to the scatter, and it is the only thing standing between a
    // hypothetical code-generation bug and a silently truncated Jacobian, so it defaults to on.
    void set_verify_frozen_sparsity(bool yesno) { verify_frozen_sparsity = yesno; }
    bool get_verify_frozen_sparsity() const { return verify_frozen_sparsity; }
    // Diagnostics/tests. nnz of the cached pattern for the CURRENT pattern id, or 0 if none is held --
    // a positive value is the only direct evidence the preallocated path engaged rather than falling back.
    unsigned get_frozen_sparsity_nnz(unsigned matrix_index=0);
    unsigned long get_frozen_sparsity_rebuild_count() const { return frozen_sparsity_rebuilds; } // Watch for cache thrashing
    unsigned long long get_frozen_sparsity_stored_entries() const { return frozen_sparsity_stored_entries; }
    unsigned long long get_frozen_sparsity_zero_entries() const { return frozen_sparsity_zero_entries; }
    void reset_frozen_sparsity_fill_stats() { frozen_sparsity_stored_entries = 0; frozen_sparsity_zero_entries = 0; }
    unsigned get_frozen_sparsity_cache_capacity() const { return frozen_sparsity_cache_capacity; }
#ifdef OOMPH_HAS_MPI
    void set_use_frozen_distributed_sparsity(bool yesno) { use_frozen_distributed_sparsity = yesno; if (!yesno) { distributed_frozen_sparsity.clear(); distributed_residual_plan.clear(); } }
    bool get_use_frozen_distributed_sparsity() const { return use_frozen_distributed_sparsity; }
    unsigned long get_distributed_frozen_rebuild_count() const { return distributed_frozen_rebuilds; }
    unsigned long get_distributed_residual_rebuild_count() const { return distributed_residual_rebuilds; }
#else
    void set_use_frozen_distributed_sparsity(bool yesno) {}
    bool get_use_frozen_distributed_sparsity() const { return false; }
    unsigned long get_distributed_frozen_rebuild_count() const { return 0; }
    unsigned long get_distributed_residual_rebuild_count() const { return 0; }
#endif
    void set_frozen_sparsity_cache_capacity(unsigned n) { frozen_sparsity_cache_capacity = (n < 1 ? 1 : n); frozen_sparsity_cache.clear(); }
    // Identifies the current Jacobian sparsity pattern. Changes whenever the pattern may have
    // changed. Solvers may reuse anything derived from the pattern (a symbolic factorisation, a
    // preallocated PETSc Mat) while this value is unchanged and non-zero.
    // Only meaningful while keep_structural_zeros is set - otherwise the pattern is value-dependent
    // and no id can describe it, so this returns 0 ("unusable"). It is deliberately NOT const: it
    // re-validates lazily against the state the pattern depends on (see the .cpp), so that a state
    // change nobody remembered to hook cannot silently hand a solver a stale pattern. A missed
    // invalidation is a wrong answer, not a crash, so this must not rely on call-site discipline alone.
    unsigned long get_jacobian_structure_id();
    // Declare every pattern seen so far dead. assign_eqn_numbers() is the main caller.
    void invalidate_jacobian_structure() { jacobian_structure_ids.clear(); frozen_sparsity_cache.clear();
#ifdef OOMPH_HAS_MPI
      distributed_frozen_sparsity.clear(); distributed_residual_plan.clear();
#endif
    }

    // Phase-0 instrumentation: run the elemental part of the assembly (get_all_vectors_and_matrices
    // for every non-halo element) n_repeat times without scattering anything into a matrix, and
    // return the average seconds per pass. Subtracting this from a full assembly gives the cost of
    // the scatter + CSR compression, which is what the structural-assembly work removes.
    double benchmark_elemental_assembly(unsigned n_repeat, bool with_jacobian, bool with_mass_matrix);

    void set_dist_problem_matrix_distribution(const std::string & mode); // Controls how the distributed Jacobian matrix is partitioned across MPI ranks
    std::string get_dist_problem_matrix_distribution() ;

    std::vector<DynamicBulkElementCode *> &get_bulk_element_codes() { return bulk_element_codes; }

    std::vector<int> get_dof_to_global_field_index_mapping(); // For each dof: the index into get_global_field_names(), or -1 if the dof cannot be attributed to a single global field
    std::vector<std::string> get_global_field_names();

    std::string get_bifurcation_tracking_mode() const { return bifurcation_tracking_mode; }
    std::vector<std::complex<double>> get_bifurcation_eigenvector();
    double get_bifurcation_omega();
    std::tuple<bool,std::complex<double>> get_bifurcation_tracking_info(); //Returns whether we are tracking a bifurcation, the eigenvalue, the azimuthal wavenumber and the cartesian normal mode if set
    std::vector<double> get_arclength_dof_derivative_vector(); // d(dof)/ds along the arclength-continuation branch
    std::vector<double> get_arclength_dof_current_vector();
    void update_dof_vectors_for_continuation(const std::vector<double> & ddof, const std::vector<double> & curr);
    void update_param_info_for_continuation(double dp,double p0);
    void set_dof_direction_arclength(std::vector<double> ddir);
    void get_dofs(oomph::DoubleVector& dofs) const  override {oomph::Problem::get_dofs(dofs);}
    void get_dofs(const unsigned& t, oomph::DoubleVector& dofs) const override; // Dofs at history time level t (t=0 is current)
    void set_dofs(const oomph::DoubleVector& dofs) override {oomph::Problem::set_dofs(dofs);}
    void set_dofs(const unsigned& t, oomph::DoubleVector& dof_pt) override;
    void set_dofs(const unsigned& t, oomph::Vector<double*>& dof_pt) override;
    // oomph-lib's adapt() has an unsigned&/unsigned& signature that cannot easily be overridden in Python;
    // _adapt() is the virtual entry point exposed/overridable there, adapt() just adapts the signature.
    void adapt(unsigned &n_refined, unsigned &n_unrefined) override
    {
      std::pair<unsigned, unsigned> res = this->_adapt();
      n_refined = res.first;
      n_unrefined = res.second;
    }
    // Max Newton/timestepping residual per iteration from the last solve, exposed for diagnostics/Python
    std::vector<double> get_last_residual_convergence()
    {
      std::vector<double> res(Max_res.size());
      for (unsigned int i = 0; i < Max_res.size(); i++)
        res[i] = Max_res[i];
      return res;
    }
    // Default adapt implementation (just forwards to oomph-lib's mesh adaptation); overridden in Python
    // subclasses via the trampoline to implement custom/load-balancing-aware adaptation.
    virtual std::pair<unsigned, unsigned> _adapt()
    {
      unsigned n_refined = 0;
      unsigned n_unrefined = 0;
      //    std::cout <<"FAKE ADAPT" << std::endl;
      oomph::Problem::adapt(n_refined, n_unrefined);
      return std::make_pair(n_refined, n_unrefined);
    }
    //   MeshTemplate* get_mesh_template();
    // Loads a compiled equation shared library (dynamic_lib) generated from element_class and registers it as a new DynamicBulkElementCode
    DynamicBulkElementCode *load_dynamic_bulk_element_code(std::string dynamic_lib, FiniteElementCode *element_class);
    //   const FieldDescriptor * get_field(const std::string & name)  {return fields_by_name[name];}
    //   const FieldDescriptor * get_field(const unsigned int & index)  {return fields_by_index[index];}

    GlobalParameterDescriptor *assert_global_parameter(const std::string &name); // Returns the descriptor for name, creating it (value 0) if it does not yet exist
    GlobalParameterDescriptor *get_global_parameter(const std::string &name) { return global_params_by_name[name]; }
    GlobalParameterDescriptor *get_global_parameter(const unsigned int &index) { return global_params_by_index[index]; }
    int resolve_parameter_value_ptr(double *ptr); // Finds the global index of the parameter whose value() address equals ptr, or -1

    // const bool has_field(const std::string & name)  {return fields_by_name.count(name)>0;}
    bool has_global_parameter(const std::string &name) { return global_params_by_name.count(name) > 0; }
    std::set<std::string> get_global_parameter_names()
    {
      std::set<std::string> res;
      for (auto const &pkeys : global_params_by_name)
        res.insert(pkeys.first);
      return res;
    }

    void ensure_dummy_values_to_be_dummy(); // Resets helper/dummy Data values (e.g. unused position dofs) back to their sentinel dummy values after a solve
    void unpin_Dirichlet_dofs_for_matrix_manipulation(); // Counterpart to the matrix-manipulation Dirichlet strategy: temporarily unpins the Dirichlet dofs so they are assembled as normal dofs
    void actions_after_adapt() override;
    unsigned long assign_eqn_numbers(const bool& assign_local_eqn_numbers = true) override; // Also (re)builds the defined-field list and pins fields with empty Jacobian rows/columns
    virtual void setup_pinning() {} // Hook for problem-specific pinning of dofs, called during equation numbering; overridden in Python
    void set_initial_condition() override; // Hook to set up initial conditions; overridden in Python (default calls the mesh-level setup_initial_conditions)
    virtual std::tuple<std::vector<double>, std::vector<bool>> get_current_dofs(); // Current dof values and, for each, whether it is a nodal POSITION dof (not whether it is pinned -- a pinned value is not a dof at all and does not appear here). See the implementation.
    virtual std::vector<double> get_history_dofs(unsigned t); // Dof values at history time level t
    virtual std::vector<double> get_current_pinned_values(bool with_pos); // Values of all pinned Data (optionally including nodal positions), used to save/restore state independent of the dof vector

    virtual void set_current_dofs(const std::vector<double> &inp);
    virtual void set_history_dofs(unsigned t, const std::vector<double> &inp);
    virtual void set_current_pinned_values(const std::vector<double> &inp,bool with_pos,unsigned t=0);
    virtual bool &always_take_one_newton_step() { return Always_take_one_newton_step; }
    virtual bool get_Keep_temporal_error_below_tolerance() { return Keep_temporal_error_below_tolerance; }
    virtual void set_Keep_temporal_error_below_tolerance(bool s) { Keep_temporal_error_below_tolerance = s; }
    /* 	 pyoomph::Mesh * mesh_pt()
       {
        return dynamic_cast<pyoomph::Mesh*>(oomph::Problem::mesh_pt());
       }*/

    double &newton_relaxation_factor() { return Relaxation_factor; }
    double &DTSF_max_increase_factor() { return DTSF_max_increase; }
    double &DTSF_min_decrease_factor() { return DTSF_min_decrease; }
    double &minimum_ds() { return Minimum_ds; }

    // Sets the (single) top-level mesh pointer; note the debug prints below are intentionally left in
    // to help diagnose mesh pointer / dynamic_cast issues and are not considered normal verbose output.
    void set_mesh_pt(pyoomph::Mesh *mesh)
    {
      std::cout << "Setting mesh " << mesh << "  " << dynamic_cast<pyoomph::Mesh *>(mesh) << std::endl;
      oomph::Problem::mesh_pt() = mesh;
      std::cout << "Getting mesh " << oomph::Problem::mesh_pt() << "  " << dynamic_cast<pyoomph::Mesh *>(oomph::Problem::mesh_pt()) << "   " << mesh_pt() << std::endl;
    }

    // Expose these to be public
    virtual void actions_after_change_in_global_parameter(const std::string &  ) {}
    virtual void actions_after_parameter_increase(const  std::string &  ) {}
    void actions_after_change_in_bifurcation_parameter() override {}
    void actions_before_newton_convergence_check() override {}
    // Also expose these oomph-lib hooks (protected there) as public: nanobind's trampoline
    // dispatch (unlike pybind11's) requires a public base binding under the same name to detect
    // whether a Python subclass has overridden the hook.
    using oomph::Problem::actions_before_newton_solve;
    using oomph::Problem::actions_after_newton_solve;
    using oomph::Problem::actions_before_newton_step;
    using oomph::Problem::actions_after_newton_step;
    #ifdef OOMPH_HAS_MPI
    using oomph::Problem::actions_before_distribute;
    using oomph::Problem::actions_after_distribute;
    #endif

    virtual void _build_mesh() { throw_runtime_error("You must implement the function _build_mesh for load_balancing"); } // Overridden in Python to (re)build the mesh; required for MPI load balancing
    #ifdef OOMPH_HAS_MPI
    void build_mesh() override {this->_build_mesh();}
    #endif
    void reset_assembly_handler_to_default() override; // Deletes any active bifurcation-tracking/custom assembly handler and restores the default one; also clears bifurcation_tracking_mode
    virtual std::vector<double> get_parameter_derivative(const std::string param); // d(residuals)/d(param) as a dense vector
    void activate_my_fold_tracking(double *const &parameter_pt, const oomph::DoubleVector &eigenvector, const bool &block_solve); // Starts fold (limit point) bifurcation tracking with a given initial null-eigenvector guess
    void activate_my_fold_tracking(double *const &parameter_pt, const bool &block_solve); // Same, but the eigenvector is determined internally
    void activate_my_pitchfork_tracking(double *const &parameter_pt, const oomph::DoubleVector &eigenvector, const bool &block_solve);
    void activate_my_hopf_tracking(double *const &parameter_pt, const double &omega, const oomph::DoubleVector &null_real, const oomph::DoubleVector &null_imag, const bool &block_solve);
    void activate_my_azimuthal_tracking(double *const &parameter_pt, const double &omega, const oomph::DoubleVector &null_real, const oomph::DoubleVector &null_imag, std::map<std::string, std::string> special_residual_forms);
    void set_arclength_parameter(std::string nam, double val); // Sets the parameter used for arclength continuation (by name) and its current value
    double arc_length_step(const std::string param, const double &ds, unsigned max_adapt); // Performs one pseudo-arclength continuation step in param with step size ds; returns the (possibly adapted) step actually taken
    double get_arc_length_parameter_derivative() { return Parameter_derivative; }
    void set_arc_length_parameter_derivative(double dp) { Parameter_derivative=dp; }
    void set_arc_length_theta_sqr(double thetasqr) {Theta_squared=thetasqr;}
    double get_arc_length_theta_sqr() {return Theta_squared;}
    // Sets up the augmented (bordered) system for tracking a bifurcation of the given typus ("fold","pitchfork","hopf","azimuthal",...)
    // in parameter param, starting from the eigenvector(s) eigenv1/eigenv2 (real/imaginary parts) and, for
    // Hopf-like bifurcations, angular frequency omega.
    void start_bifurcation_tracking(const std::string param, const std::string typus, const bool &blocksolve, const std::vector<double> &eigenv1, const std::vector<double> &eigenv2, const double &omega, std::map<std::string, std::string> special_residual_forms);
    //void start_custom_augmented_system(oomph::AssemblyHandler *handler);
    void reset_augmented_dof_vector_to_nonaugmented(); // Discards any augmentation (bifurcation tracking, arclength, custom) dofs and returns to the plain physical dof vector
    void add_augmented_dofs(DofAugmentations &aug); // Appends the dofs registered in aug to the problem's dof vector
    DofAugmentations * create_dof_augmentation() {return new DofAugmentations(this);}
    void start_orbit_tracking(const std::vector<std::vector<double>> &history, const double &T,int bspline_order,int gl_order,std::vector<double> knots,unsigned T_constraint_mode); // Sets up periodic-orbit tracking from an initial guessed history (time series of dof snapshots) with period T, represented via B-splines
    void after_bifurcation_tracking_step(); // Post-processing hook called after each continuation step while bifurcation tracking is active (e.g. to renormalize the eigenvector)
    double &global_parameter(const std::string &n); // Reference to the value() of the named global parameter (creating it if necessary)

    // Required for custom bifurcation trackers
    oomph::Vector<double *> &GetDofPtr() { return this->Dof_pt; }
    oomph::LinearAlgebraDistribution *GetDofDistributionPt() { return this->Dof_distribution_pt; }
    oomph::Vector<oomph::Vector<unsigned>> &GetSparcseAssembleWithArraysPA() { return this->Sparse_assemble_with_arrays_previous_allocation; }

    virtual void quiet(bool _quiet); // Suppresses/re-enables oomph-lib's and pyoomph's own informational output
    virtual bool _set_solved_residual(std::string name, bool raise_error=true,bool remove_dofs_without_jacobian_row=true); // Switches which named residual (see residual_names) subsequent assembly/solves act on
    bool has_empty_jacobian_rows_marked() const; // Whether the last assemble_defined_field_list()/assign_eqn_numbers() found fields with empty Jacobian rows/cols that had to be pinned
    virtual void _replace_RJM_by_param_deriv(std::string name,bool active); // Toggles replacing the residual/Jacobian/mass-matrix assembly by the derivative w.r.t. parameter name (used internally for parameter-derivative computations)
    virtual std::string _get_solved_residual() { return _solved_residual; }
    virtual bool is_quiet() const { return _is_quiet; }
    // void set_diagonal_zero_entries(bool yesno) {KeepZeroDiagonal=yesno;} //Requires a patched oomph-lib problem class
    Problem();
    virtual void unload_all_dlls(bool clear_all=true); // Closes all loaded DynamicBulkElementCode shared libraries (called on destruction / explicit cleanup, e.g. before recompiling equations)
    virtual unsigned get_max_dt_order() const; // Maximum time-derivative order required by any of the loaded element codes (determines how many history values the timestepper must keep)
    ~Problem() override;
    virtual CCompiler *get_ccompiler() { return compiler; }
    virtual void set_ccompiler(CCompiler *comp) { compiler = comp; }
    virtual void assemble_eigenproblem_matrices(oomph::CRDoubleMatrix *&M, oomph::CRDoubleMatrix *&J, double sigma_r); // Assembles the mass matrix M and (shifted) Jacobian J for a generalized eigenvalue problem J*v = sigma*M*v around shift sigma_r

    // Must be overridden (in Python) whenever use_custom_residual_jacobian is set: fills info with
    // user-supplied residuals/Jacobian instead of relying on elemental assembly.
    virtual void  get_custom_residuals_jacobian(CustomResJacInformation * )
    {
     throw_runtime_error("Must be implemented");
    }

    // Thin wrappers around oomph::Problem's elemental-assembly residual/Jacobian/parameter-derivative
    // routines, kept virtual so that get_residuals/get_jacobian/get_derivative_wrt_global_parameter below
    // can dispatch to either these (normal elemental assembly) or the custom-residual-Jacobian path.
    virtual void get_jacobian_by_elemental_assembly(oomph::DoubleVector &residuals,oomph::CRDoubleMatrix &jacobian)
    {
        oomph::Problem::get_jacobian(residuals,jacobian);
    }
    virtual void get_residuals_by_elemental_assembly(oomph::DoubleVector &residuals)
    {
     oomph::Problem::get_residuals(residuals);
    }
    virtual void get_derivative_wrt_global_parameter_elemental_assembly(double* const& parameter_pt,oomph::DoubleVector &result)
    {
     oomph::Problem::get_derivative_wrt_global_parameter(parameter_pt,result);
    }
    // Top-level entry points for residual/Jacobian/parameter-derivative assembly: dispatch between
    // normal elemental assembly and the custom-residual-Jacobian path (use_custom_residual_jacobian),
    // and additionally apply the matrix-manipulation Dirichlet enforcement when that strategy is active.
    void get_residuals(oomph::DoubleVector &residuals) override;
    // Abort the Newton solve currently running, without touching the dofs.
    //
    // Replaces the old mechanism, which multiplied the whole dof vector by 1e40 and added noise so
    // that the NEXT residual evaluation would exceed max_residuals and make oomph-lib throw. Three
    // things were wrong with that: it destroyed the state, so nothing could be inspected or recovered
    // afterwards; it went through get_current_dofs()/set_current_dofs(), which redistribute and are
    // therefore COLLECTIVE, while the decision to reject is typically partition-dependent -- so a
    // rejection seen by only some ranks deadlocked; and it paid for a full extra residual assembly to
    // communicate one bit. This sets a flag that the next get_residuals() consumes, agreeing it across
    // ranks first. The reason is reported when it fires.
    void request_newton_abort(const std::string &reason);
    bool newton_abort_requested() const { return newton_abort_flag; }
  protected:
    bool newton_abort_flag = false;
    std::string newton_abort_reason;
    // True (having reported the reason) if an abort was requested on ANY rank, in which case the
    // caller must not assemble. Clears the request, so it fires once.
    bool consume_newton_abort_request();
  public:
    void get_jacobian(oomph::DoubleVector &residuals,oomph::CRDoubleMatrix &jacobian) override;
    void get_derivative_wrt_global_parameter(double* const& parameter_pt,oomph::DoubleVector& result) override;
    virtual void remove_dirichlets_by_matrix_manipulation(oomph::DoubleVector &residuals,oomph::CRDoubleMatrix *jacobian=NULL); // Zeroes out rows/columns of Dirichlet-pinned dofs and sets the residual to the constraint violation, in-place on residuals/jacobian

    virtual SparseRank3Tensor assemble_hessian_tensor(bool symmetric); // Assembles the full second-derivative (Hessian) tensor d^2(residual)/d(dof)^2, needed e.g. for bifurcation normal-form/branch-switching computations
    virtual std::vector<double> get_second_order_directional_derivative(std::vector<double> dir); // Directional second derivative of the residuals along dir, computed without forming the full Hessian tensor

    virtual void set_symmetric_hessian_assembly(bool active) {symmetric_hessian_assembly=active;}
    virtual bool get_symmetric_hessian_assembly() const {return symmetric_hessian_assembly;}

    #ifndef OOMPH_HAS_MPI
    virtual void actions_before_distribute() {}
    virtual void actions_after_distribute() {}
    #endif

    void set_FD_step_used_in_get_hessian_vector_products(double step) {FD_step_used_in_get_hessian_vector_products=step;}

    //	 virtual bool _globally_convergent_newton_method() {return Use_globally_convergent_newton_method;} // Damn this private decl
    void open_log_file(const std::string & fname,const bool & activate_logging=true); // Opens fname for logging of solver/Newton diagnostics; pass activate_logging=false to just set the path without starting to log yet

    // Combined assembly of several different requested quantities ("what": residuals, Jacobian, mass
    // matrix, Hessian-vector products, parameter derivatives, ...) restricted to given residual
    // contributions/parameters in a single elemental loop, to avoid redundant element traversals when
    // multiple quantities are needed at once (e.g. by the Python-side continuation/bifurcation code).
    // Results are returned via the output parameters (data/csrdata for dense/sparse pieces, ndof, return_indices).
    void assemble_multiassembly(std::vector<std::string> what,std::vector<std::string> contributions,std::vector<std::string> params,std::vector<std::vector<double>> & hessian_vectors,std::vector<unsigned> & hessian_vector_indices,std::vector<std::vector<double>> & data,std::vector<std::vector<int>> &csrdata,unsigned & ndof,std::vector<int> & return_indices);

  };

  void RequiredShapes_merge(JITFuncSpec_RequiredShapes_FiniteElement_t *src, JITFuncSpec_RequiredShapes_FiniteElement_t *dest); // Merges the "required shapes" flags of src into dest (union of what shape information the elements need)
  void RequiredShapes_free(JITFuncSpec_RequiredShapes_FiniteElement_t *p);
}
