/*================================================================================
pyoomph - a multi-physics finite element framework based on oomph-lib and GiNaC 
Copyright (C) 2021-2026  Christian Diddens, Duarte Rocha & Maxim de Wildt

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>. 

The main author may be contacted at c.diddens@utwente.nl

================================================================================*/


#pragma once

#include "oomph_lib.hpp"

#include <vector>
#include <map>
#include <unordered_set>
#include <memory>

#include "jitbridge.h"
#include "mesh.hpp"

#include "hessian_tensor.hpp"

namespace pyoomph
{

  // class MeshTemplate;
  class Problem;
  class DynamicBulkElementInstance;
  class FiniteElementCode;
  class CCompiler;

  // Represents one compiled equation code, i.e. one shared library generated by the JIT code
  // generator (GiNaC symbolic equations -> C code -> compiled .so) for a single FiniteElementCode
  // (a bulk domain or an interface). A single DynamicBulkElementCode can be instantiated (via
  // factory_instance) on multiple meshes/domains, each giving a DynamicBulkElementInstance.
  class DynamicBulkElementCode
  {
  protected:
    friend class Problem;
    friend class DynamicBulkElementInstance;
    Problem *problem;
    CCompiler *compiler;
    std::string filename;
    JITFuncSpec_Table_FiniteElement_t *functable; // Function table exported by the compiled .so, containing all residual/jacobian/etc. callbacks
    FiniteElementCode *element_class; // The symbolic (GiNaC-based) code generator this binary was compiled from
    std::map<std::string, int> integral_function_map,extremum_function_map; // Name -> index lookup for integral/extremum diagnostic functions exposed by the code
    void *so_handle; // dlopen() handle of the loaded shared library

  public:
    const std::string &get_file_name() const { return filename; }
    DynamicBulkElementCode(Problem *prob, CCompiler *ccompiler, std::string fnam, FiniteElementCode *elem);
    virtual ~DynamicBulkElementCode(); // Closes the shared library handle
    // Creates a new instance of this code bound to a specific bulk mesh (fields, external data links, etc. are then resolved per-instance)
    DynamicBulkElementInstance *factory_instance(pyoomph::Mesh *bulkmesh);
    const JITFuncSpec_Table_FiniteElement_t *get_func_table() const { return functable; }
    JITFuncSpec_Table_FiniteElement_t *get_func_table() { return functable; }
    int get_max_dt_order() const { return get_func_table()->max_dt_order; }
    int get_integral_function_index(std::string n); // -1 if not present
    int get_extremum_function_index(std::string n); // -1 if not present
    unsigned _set_solved_residual(std::string name);
    FiniteElementCode *get_code() { return element_class; }
  };

  // enum FieldSpace {C1=1, C2=2};

  // A single link from an element to an "external" (i.e. not one of its own nodal/internal) Data object,
  // e.g. a coupling to a value living on another domain/mesh, or a global parameter exposed as Data.
  class ExternalDataLink
  {
  public:
    oomph::Data *data;   // External data object
    int value_index;     // Value of this external data to be taken
    int elemental_index; // Index of the external_data_pt inside the element
    ExternalDataLink(oomph::Data *d, int v) : data(d), value_index(v), elemental_index(-1) {}
  };

  // Collection of ExternalDataLinks for one DynamicBulkElementInstance, with deduplication of the
  // underlying Data pointers so that each distinct external Data object is only added once per element.
  class ExternalDataLinkVector : public std::vector<ExternalDataLink>
  {
  protected:
    std::vector<oomph::Data *> elemental_data; // Deduplicated list of Data objects that must be registered as external data on the element

  public:
    ExternalDataLinkVector(unsigned n) : std::vector<ExternalDataLink>(n, ExternalDataLink(NULL, -1)) {}
    void reindex_elemental_data(); // Rebuilds elemental_data from the (possibly sparsely filled) link entries, removing duplicates
    std::vector<oomph::Data *> &get_required_external_data() { return elemental_data; }
  };



  // A concrete instantiation of a DynamicBulkElementCode (one compiled .so) on a specific bulk mesh,
  // i.e. "load one .so -> instantiate for different fields (with different parameter sets)".
  // Multiple instances can share the same compiled code but bind to different meshes/field name mappings.
  class DynamicBulkElementInstance
  {
  protected:
    friend class DynamicBulkElementCode;
    friend class Problem;
    friend class FiniteElementCode;
    friend class BulkElementBase;
    DynamicBulkElementCode *dyn;
    DynamicBulkElementInstance(DynamicBulkElementCode *d, pyoomph::Mesh *bm);
    //  std::vector<int> local_field_to_global_field_index_C1;
    //  std::vector<int> local_field_to_global_field_index_C2;
    //  std::vector<int> local_global_parameter_to_global_index;
    ExternalDataLinkVector linked_external_data;
    pyoomph::Mesh *bulkmesh; // Bulk mesh -> required to identify interface field indices
  public:
    std::set<int> nullify_bulk_residuals; // indices to nullify bulk residual contributions of continuous spaces at interface, negative is position dof
    void link_external_data(std::string name, oomph::Data *data, int index,std::string full_source_name);
    Problem *get_problem() { return dyn->problem; }
    pyoomph::Mesh *get_bulk_mesh() { return bulkmesh; }
    std::map<std::string, unsigned> setup_interface_dof_indices(); // Populates the interface_dof_indices array in the space_info of the functable. This is required for continuous fields (C2TB-C1) to identify the additional dofs on interface nodes
    void set_bulk_mesh(pyoomph::Mesh *m) { bulkmesh = m; }
    FiniteElementCode *get_element_class() { return dyn->element_class; }
    void sanity_check(); // Consistency checks of the instance's field/external-data setup against the compiled function table; throws on failure
    DynamicBulkElementCode *get_code() { return dyn; }
    const DynamicBulkElementCode *get_code() const { return dyn; }
    bool has_parameter_contribution(const std::string  & param); // Whether the compiled code has a (residual/jacobian) contribution depending on the given global parameter
    /*void bind_field(const std::string & internal_name,const std::string & global_name);
    void bind_field(unsigned int index,std::string name,FieldSpace space);
    void bind_field_C1(unsigned int index,std::string name) {bind_field(index,name,L1);}
    void bind_field_C2(unsigned int index,std::string name) {bind_field(index,name,L2);}*/
    //  void bind_global_parameter(const std::string & internal_name, const std::string & global_name);
    // unsigned int get_num_fields_C1() const {return dyn->functable->numfields_C1;}
    //  int get_global_field_index_C1(const unsigned int & i) const {return local_field_to_global_field_index_C1[i];}
    // unsigned int get_num_fields_C2() const {return dyn->functable->numfields_C2;}
    bool can_be_time_adaptive() const { return dyn->functable->has_temporal_estimators; }
    //  int get_global_field_index_C2(const unsigned int & i) const {return local_field_to_global_field_index_C2[i];}
    unsigned int get_num_global_parameters() const { return dyn->functable->numglobal_params; }
    //  int get_global_parameter_index(const unsigned int & i) const {return local_global_parameter_to_global_index[i];}
    const JITFuncSpec_Table_FiniteElement_t *get_func_table() const { return dyn->get_func_table(); }
    JITFuncSpec_Table_FiniteElement_t *get_func_table() { return dyn->get_func_table(); }
    int get_max_dt_order() const { return dyn->get_max_dt_order(); }
    int get_nodal_field_index(std::string name);
    std::map<std::string, unsigned> get_nodal_field_indices();
    std::map<std::string, unsigned> get_elemental_field_indices();
    int get_discontinuous_field_index(std::string name);
    int get_integral_function_index(std::string n) { return dyn->get_integral_function_index(n); }
    int get_extremum_function_index(std::string n) { return dyn->get_extremum_function_index(n); }
    unsigned resolve_interface_dof_id(std::string n);
    std::string get_space_of_field(std::string name);
    bool has_moving_nodes() {return dyn->functable->moving_nodes;}
    ExternalDataLinkVector &get_linked_external_data() { return linked_external_data; }
  };

  class Problem;
  /*
  class FieldDescriptor
  {
   protected:
    std::string name;
    FieldSpace space;
    unsigned int global_index;
    Problem * problem;
   public:
    FieldDescriptor(Problem * p,const std::string & n, const FieldSpace & s, const unsigned int & gi) : name(n), space(s), global_index(gi), problem(p) {}
    const std::string & get_name() const {return name;}
    const FieldSpace & get_space() const {return space;}
    const unsigned int & get_global_index() const {return global_index;}
  };
  */

  // A single named global parameter (e.g. a scalar problem parameter used in the GiNaC equations
  // and exposed to Python via GiNaC_GlobalParam). Holds the actual double value and its global index
  // within the Problem's parameter list; the value itself is what oomph-lib's continuation/parameter
  // machinery takes a pointer to (via value()).
  class GlobalParameterDescriptor
  {
  protected:
    std::string name;
    unsigned int global_index;
    Problem *problem;
    double Value;
    bool positive=false; // If true, the parameter is restricted to non-negative values (enforced on write, e.g. from Python)
  public:
    GlobalParameterDescriptor(Problem *p, const std::string &n, const unsigned int &gi) : name(n), global_index(gi), problem(p), Value(0.0) {}
    const std::string &get_name() const { return name; }
    const unsigned int &get_global_index() const { return global_index; }
    double &value() { return Value; }
    const double &value() const { return Value; }
    void restrict_to_positive_values() {positive=true;}
    bool is_restricted_to_positive_values() const { return positive;}
    void set_analytic_derivative(bool active); // Toggle whether derivatives w.r.t. this parameter are obtained analytically (from the generated code) or by finite differences
    bool get_analytic_derivative();
    Problem *get_problem() { return problem; }
  };

  // Buffer used to pass a custom (user/Python-supplied) residual vector and Jacobian matrix (CSR) into
  // the assembly machinery, bypassing the normal elemental assembly. Used by Problem::get_custom_residuals_jacobian.
  class CustomResJacInformation
  {
   protected:
      friend class Problem;
      bool Require_jacobian; // Whether the caller actually needs the Jacobian (or just the residuals)
      std::string dparameter; // Name of the parameter w.r.t. which a derivative is requested, if any
      std::vector<double> residuals;
      oomph::Vector<double> Jvals;
      oomph::Vector<int> Jcolumn_index,Jrow_start;
   public:
      bool require_jacobian() const {return Require_jacobian;}
      void set_custom_residuals(const std::vector<double> & r) {residuals=r;}
      void set_custom_jacobian(const std::vector<double> & Jv, const std::vector<int> & col_index,const std::vector<int> & row_start);
      std::string get_parameter_name() const {return dparameter;}
      CustomResJacInformation(bool req_J,std::string parameter_name) : Require_jacobian(req_J), dparameter(parameter_name) {}
  };

  // Manages additional ("augmented") degrees of freedom that are appended to the normal dof vector,
  // e.g. extra scalar/vector unknowns and parameters introduced by constraints (arclength continuation,
  // phase conditions, etc). Vectors/scalars/parameters are registered via add_vector/add_scalar/add_parameter
  // before finalization, and split() can later decompose a full augmented dof vector back into its parts.
  class DofAugmentations
  {
    protected:
      friend class pyoomph::Problem;
      Problem * problem;
      std::vector<unsigned> types,split_offsets; // Per-entry type tag and offset (in the augmented dof block) used to reconstruct split()
      unsigned total_length; // Total number of augmented dofs added so far
      std::vector<std::vector<double>> augmented_vectors;
      std::vector<double> augmented_scalars;
      std::vector<std::string> augmented_parameters;
      bool finalized;
    public:
      DofAugmentations(Problem * _problem);
      unsigned add_vector(const std::vector<double> & v); // Registers a vector of augmented dofs, returns its offset
      unsigned add_scalar(const double & s); // Registers a single augmented scalar dof, returns its offset
      unsigned add_parameter(std::string); // Registers a global parameter as an augmented dof, returns its offset
      std::vector<std::vector<double>> split(unsigned startindex,int endindex); // Splits the augmented part of the dof vector back into the individually registered pieces

  };

  // Bookkeeping used when Dirichlet conditions are enforced by post-hoc matrix/residual manipulation
  // rather than by removing the corresponding dofs from the dof vector (see
  // Problem::dirichlets_by_removing_from_dof_vector). Tracks which (Data, index) pairs are pinned by
  // a Dirichlet condition and the corresponding set of global equation numbers.
  class DirichletMatrixManipulationInfo
  {
    protected:
      std::map<oomph::Data *,std::set<unsigned>> data_to_dirichlet_dof_indices;
      //std::map<unsigned long, double*> eqn_number_to_value_ptr;
      std::unordered_set<unsigned long> global_pinned_dof_set; // Global equation numbers that are Dirichlet-pinned, built by build_global_pinned_equation_set()
    public:
      void clear();
      void add_dirichlet_dof(oomph::Data *d, unsigned dof_index);
      //void build_equation_to_value_map();
      void build_global_pinned_equation_set(Problem *prob); // (Re)builds global_pinned_dof_set from data_to_dirichlet_dof_indices using the problem's current equation numbering
      const std::unordered_set<unsigned long> & get_global_pinned_equation_set() const {return global_pinned_dof_set;}
      //const std::map<unsigned long, double*> &get_eqn_number_to_value_map() const { return eqn_number_to_value_ptr; }

  };

  // The central orchestrator of a pyoomph simulation. Derives from oomph::Problem and adds:
  //  - management of the JIT-compiled equation codes (DynamicBulkElementCode/-Instance) and global parameters
  //  - the "defined field" bookkeeping used to detect empty Jacobian rows/columns (fields that must be pinned)
  //  - bifurcation/continuation tracking (fold, pitchfork, Hopf, azimuthal symmetry breaking, periodic orbits)
  //  - Hessian assembly for second-order (bifurcation/optimization) computations
  //  - custom sparse assembly, Dirichlet handling (either by dof removal or by matrix manipulation), logging
  // Most of the heavy lifting is implemented in problem.cpp; this header is the primary interface used both
  // from C++ (e.g. by generated element code, bifurcation.cpp) and from Python via src/pybind/problem.cpp.
  class Problem : public oomph::Problem
  {
  protected:
    CCompiler *compiler; // C compiler front-end used to compile the JIT-generated equation code into shared libraries
    std::ofstream * logfile;
    bool _is_quiet;
    friend class DynamicBulkElementInstance;
    //	 MeshTemplate *meshtemplate;
    std::vector<DynamicBulkElementCode *> bulk_element_codes; // All compiled equation codes loaded so far (owned by the Problem)
    //   std::map<std::string,FieldDescriptor*> fields_by_name;
    //   std::vector<FieldDescriptor*> fields_by_index;
    std::map<std::string, GlobalParameterDescriptor *> global_params_by_name;
    std::vector<GlobalParameterDescriptor *> global_params_by_index; // Indexed by GlobalParameterDescriptor::get_global_index()
    //   const FieldDescriptor * assert_field(const std::string & name,const FieldSpace & space );

    oomph::CRDoubleMatrix *eigen_JacobianMatrixPt, *eigen_MassMatrixPt; // Cached Jacobian/mass matrices from the last assemble_eigenproblem_matrices() call
    double global_temporal_error_norm(); // Combines the per-mesh temporal error norm contributions into a single global error estimate used for adaptive timestepping
    std::string bifurcation_tracking_mode = ""; // "", "fold", "pitchfork", "hopf", "azimuthal", ... - empty means no bifurcation tracking is active
    std::string _solved_residual = ""; // Name of the currently active residual (multi-residual problems can switch which residual/Jacobian assign_eqn_numbers/get_jacobian operate on); "" means the default combined residual
    bool symmetric_hessian_assembly=true; // Whether the Hessian tensor assembly exploits the symmetry of the second derivative (faster, but requires the underlying form to actually be symmetric)
    // If true, we do it the oomph-lib way (remove dofs of Dirichlet). If false, all Dirichlets are kept as dofs and the system is manipulated afterwards
    // (note: completely pinned fields without any weak formulation (usually helper field, e.g. references for normalized arclength etc) are always removed from the dofs, independent of this setting)
    bool dirichlets_by_removing_from_dof_vector=true;

    void actions_after_change_in_global_parameter(double *const &parameter_pt) override; // oomph-lib hook: resolves parameter_pt to its name and forwards to the string-named overload below
    void actions_after_parameter_increase(double *const &parameter_pt) override;

    double lambda_tracking_real = 0.0; // Real(lambda) for tracking of eigenbranches
    virtual void sparse_assemble_row_or_column_compressed_for_periodic_orbit(oomph::Vector<int*>& column_or_row_index,oomph::Vector<int*>& row_or_column_start,oomph::Vector<double*>& value,oomph::Vector<unsigned>& nnz,oomph::Vector<double*>& residuals,bool compressed_row_flag); // Specialized sparse assembly for the augmented system used during periodic orbit tracking
    void sparse_assemble_row_or_column_compressed(oomph::Vector<int*>& column_or_row_index,oomph::Vector<int*>& row_or_column_start,oomph::Vector<double*>& value,oomph::Vector<unsigned>& nnz,oomph::Vector<double*>& residual,bool compressed_row_flag) override; // Dispatches to the base-problem or periodic-orbit assembly depending on the active assembly handler
    unsigned n_unaugmented_dofs=0; // Number of dofs of the "physical" problem, i.e. excluding any bifurcation-tracking/arclength augmentation dofs
    std::vector<std::string> defined_fields; // All globally known field names (across all domains), used for the empty-Jacobian-row/col analysis
    std::vector<DynamicBulkElementCode*> defined_fields_to_domain; // Parallel to defined_fields: the code (domain) each field was defined in
    std::vector<std::string> residual_names; // Names of all residuals defined in the problem (for multi-residual/multi-assembly problems)
    std::vector<std::vector<bool>> residual_contributing_fields; // [residual][defined_field] -> whether the defined field contributes to the residual (i.e. whether there is a least a test function contributing to it)
    std::vector<std::vector<std::vector<bool>>> jacobian_contributing_fields; // [residual][defined_field][defined_field] -> whether the jacobian has a contribution from the derivative of the residual w.r.t. the defined field (i.e. whether there is at least a test function and trial function contributing to it)
    std::vector<std::vector<std::set<DynamicBulkElementCode*>>> residual_contributing_codes; // [residual][defined_field] -> Contributions to the residual from the different codes (e.g. bulk, interface, different domains)
    std::vector<std::vector<std::vector<std::set<DynamicBulkElementCode*>>>> jacobian_contributing_codes; // [residual][defined_field][defined_field] -> Contributions to the jacobian from the different codes (e.g. bulk, interface, different domains)
    std::vector<std::vector<bool>> pin_due_to_empty_jacobian_row_or_col; // [residual][defined_field] -> whether this field has to be pinned due to an empty jacobian row (i.e. no contributions on the current residual which leads to a non-invertible jacobian)
    std::vector<bool> removed_fields_due_to_missing_jacobian_row_or_col; // [defined_field] -> whether this field has been removed from the dofs due to missing jacobian row (i.e. no contributions on any residual, which leads to a non-invertible jacobian)
    std::vector<std::map<unsigned,unsigned>> global_eqs_to_jacobian_buffer_index; // [global col][global row]->[index in the jacobian buffer]

    DirichletMatrixManipulationInfo dirichlet_info;  // only used if not dirichlets_by_removing_from_dof_vector
  public:

    bool are_Dirichlets_by_removing_from_dof_vector() const { return dirichlets_by_removing_from_dof_vector; }
    // Switches between the two Dirichlet-enforcement strategies (see dirichlets_by_removing_from_dof_vector); no-op if unchanged
    void set_Dirichlets_by_removing_from_dof_vector(bool v) {
      if (v==dirichlets_by_removing_from_dof_vector) return; // No change
      // TODO: Check here whether the problem is already initialized and throw an error if this is the case, since changing this after initialization would require a reinitialization of the problem
      dirichlets_by_removing_from_dof_vector=v;
    }
    void assemble_defined_field_list(); // (Re)builds defined_fields/defined_fields_to_domain and the residual/jacobian-contribution tables from all currently loaded bulk element codes
    void update_jacobian_csr_structure(); // Rebuilds global_eqs_to_jacobian_buffer_index after the equation numbering or sparsity pattern has changed
    std::tuple<std::string,bool> get_jacobian_information_string(); // Human-readable report of which fields/residuals contribute to the Jacobian (and whether any dofs had to be pinned due to empty rows/cols), for debugging singular Jacobians
    void sparse_assemble_row_or_column_compressed_base_problem(oomph::Vector<int*>& column_or_row_index,oomph::Vector<int*>& row_or_column_start,oomph::Vector<double*>& value,oomph::Vector<unsigned>& nnz,oomph::Vector<double*>& residuals,bool compressed_row_flag); // The "normal" (non-periodic-orbit) sparse assembly, used as fallback by sparse_assemble_row_or_column_compressed()
    unsigned get_n_unaugmented_dofs() const {return n_unaugmented_dofs;}
    bool use_custom_residual_jacobian=false; // If true, residuals/Jacobian are supplied by get_custom_residuals_jacobian() instead of elemental assembly
    bool improved_pitchfork_tracking_on_unstructured_meshes=false;
    bool is_field_removed_from_dofs_due_to_missing_jacobian_row(int global_field_index);

    double * get_lambda_tracking_real() {return &lambda_tracking_real;}

    void set_sparse_assembly_method(const std::string & method); // Selects the sparse assembly implementation (oomph-lib's built-in variants, e.g. "default","single_thread","openmp_...")
    std::string get_sparse_assembly_method();

    void set_dist_problem_matrix_distribution(const std::string & mode); // Controls how the distributed Jacobian matrix is partitioned across MPI ranks
    std::string get_dist_problem_matrix_distribution() ;

    std::vector<DynamicBulkElementCode *> &get_bulk_element_codes() { return bulk_element_codes; }

    std::vector<int> get_dof_to_global_field_index_mapping(); // For each dof: the index into get_global_field_names(), or -1 if the dof cannot be attributed to a single global field
    std::vector<std::string> get_global_field_names();

    std::string get_bifurcation_tracking_mode() const { return bifurcation_tracking_mode; }
    std::vector<std::complex<double>> get_bifurcation_eigenvector();
    double get_bifurcation_omega();
    std::tuple<bool,std::complex<double>> get_bifurcation_tracking_info(); //Returns whether we are tracking a bifurcation, the eigenvalue, the azimuthal wavenumber and the cartesian normal mode if set
    std::vector<double> get_arclength_dof_derivative_vector(); // d(dof)/ds along the arclength-continuation branch
    std::vector<double> get_arclength_dof_current_vector();
    void update_dof_vectors_for_continuation(const std::vector<double> & ddof, const std::vector<double> & curr);
    void update_param_info_for_continuation(double dp,double p0);
    void set_dof_direction_arclength(std::vector<double> ddir);
    void get_dofs(oomph::DoubleVector& dofs) const  override {oomph::Problem::get_dofs(dofs);}
    void get_dofs(const unsigned& t, oomph::DoubleVector& dofs) const override; // Dofs at history time level t (t=0 is current)
    void set_dofs(const oomph::DoubleVector& dofs) override {oomph::Problem::set_dofs(dofs);}
    void set_dofs(const unsigned& t, oomph::DoubleVector& dof_pt) override;
    void set_dofs(const unsigned& t, oomph::Vector<double*>& dof_pt) override;
    // oomph-lib's adapt() has an unsigned&/unsigned& signature that cannot easily be overridden in Python;
    // _adapt() is the virtual entry point exposed/overridable there, adapt() just adapts the signature.
    void adapt(unsigned &n_refined, unsigned &n_unrefined) override
    {
      std::pair<unsigned, unsigned> res = this->_adapt();
      n_refined = res.first;
      n_unrefined = res.second;
    }
    // Max Newton/timestepping residual per iteration from the last solve, exposed for diagnostics/Python
    std::vector<double> get_last_residual_convergence()
    {
      std::vector<double> res(Max_res.size());
      for (unsigned int i = 0; i < Max_res.size(); i++)
        res[i] = Max_res[i];
      return res;
    }
    // Default adapt implementation (just forwards to oomph-lib's mesh adaptation); overridden in Python
    // subclasses via the trampoline to implement custom/load-balancing-aware adaptation.
    virtual std::pair<unsigned, unsigned> _adapt()
    {
      unsigned n_refined = 0;
      unsigned n_unrefined = 0;
      //    std::cout <<"FAKE ADAPT" << std::endl;
      oomph::Problem::adapt(n_refined, n_unrefined);
      return std::make_pair(n_refined, n_unrefined);
    }
    //   MeshTemplate* get_mesh_template();
    // Loads a compiled equation shared library (dynamic_lib) generated from element_class and registers it as a new DynamicBulkElementCode
    DynamicBulkElementCode *load_dynamic_bulk_element_code(std::string dynamic_lib, FiniteElementCode *element_class);
    //   const FieldDescriptor * get_field(const std::string & name)  {return fields_by_name[name];}
    //   const FieldDescriptor * get_field(const unsigned int & index)  {return fields_by_index[index];}

    GlobalParameterDescriptor *assert_global_parameter(const std::string &name); // Returns the descriptor for name, creating it (value 0) if it does not yet exist
    GlobalParameterDescriptor *get_global_parameter(const std::string &name) { return global_params_by_name[name]; }
    GlobalParameterDescriptor *get_global_parameter(const unsigned int &index) { return global_params_by_index[index]; }
    int resolve_parameter_value_ptr(double *ptr); // Finds the global index of the parameter whose value() address equals ptr, or -1

    // const bool has_field(const std::string & name)  {return fields_by_name.count(name)>0;}
    const bool has_global_parameter(const std::string &name) { return global_params_by_name.count(name) > 0; }
    std::set<std::string> get_global_parameter_names()
    {
      std::set<std::string> res;
      for (auto const &pkeys : global_params_by_name)
        res.insert(pkeys.first);
      return res;
    }

    void ensure_dummy_values_to_be_dummy(); // Resets helper/dummy Data values (e.g. unused position dofs) back to their sentinel dummy values after a solve
    void unpin_Dirichlet_dofs_for_matrix_manipulation(); // Counterpart to the matrix-manipulation Dirichlet strategy: temporarily unpins the Dirichlet dofs so they are assembled as normal dofs
    virtual void actions_after_adapt();
    unsigned long assign_eqn_numbers(const bool& assign_local_eqn_numbers = true) override; // Also (re)builds the defined-field list and pins fields with empty Jacobian rows/columns
    virtual void setup_pinning() {} // Hook for problem-specific pinning of dofs, called during equation numbering; overridden in Python
    virtual void set_initial_condition(); // Hook to set up initial conditions; overridden in Python (default calls the mesh-level setup_initial_conditions)
    virtual std::tuple<std::vector<double>, std::vector<bool>> get_current_dofs(); // Current dof values and, for each, whether it is pinned
    virtual std::vector<double> get_history_dofs(unsigned t); // Dof values at history time level t
    virtual std::vector<double> get_current_pinned_values(bool with_pos); // Values of all pinned Data (optionally including nodal positions), used to save/restore state independent of the dof vector

    virtual void set_current_dofs(const std::vector<double> &inp);
    virtual void set_history_dofs(unsigned t, const std::vector<double> &inp);
    virtual void set_current_pinned_values(const std::vector<double> &inp,bool with_pos,unsigned t=0);
    virtual bool &always_take_one_newton_step() { return Always_take_one_newton_step; }
    virtual bool get_Keep_temporal_error_below_tolerance() { return Keep_temporal_error_below_tolerance; }
    virtual void set_Keep_temporal_error_below_tolerance(bool s) { Keep_temporal_error_below_tolerance = s; }
    /* 	 pyoomph::Mesh * mesh_pt()
       {
        return dynamic_cast<pyoomph::Mesh*>(oomph::Problem::mesh_pt());
       }*/

    double &newton_relaxation_factor() { return Relaxation_factor; }
    double &DTSF_max_increase_factor() { return DTSF_max_increase; }
    double &DTSF_min_decrease_factor() { return DTSF_min_decrease; }
    double &minimum_ds() { return Minimum_ds; }

    // Sets the (single) top-level mesh pointer; note the debug prints below are intentionally left in
    // to help diagnose mesh pointer / dynamic_cast issues and are not considered normal verbose output.
    void set_mesh_pt(pyoomph::Mesh *mesh)
    {
      std::cout << "Setting mesh " << mesh << "  " << dynamic_cast<pyoomph::Mesh *>(mesh) << std::endl;
      oomph::Problem::mesh_pt() = mesh;
      std::cout << "Getting mesh " << oomph::Problem::mesh_pt() << "  " << dynamic_cast<pyoomph::Mesh *>(oomph::Problem::mesh_pt()) << "   " << mesh_pt() << std::endl;
    }

    // Expose these to be public
    virtual void actions_after_change_in_global_parameter(const std::string &  paramname) {}
    virtual void actions_after_parameter_increase(const  std::string &  paramname) {}
    virtual void actions_after_change_in_bifurcation_parameter() {}
    virtual void actions_before_newton_convergence_check() {}

    virtual void _build_mesh() { throw_runtime_error("You must implement the function _build_mesh for load_balancing"); } // Overridden in Python to (re)build the mesh; required for MPI load balancing
    #ifdef OOMPH_HAS_MPI
    void build_mesh() override {this->_build_mesh();}
    #endif
    void reset_assembly_handler_to_default() override; // Deletes any active bifurcation-tracking/custom assembly handler and restores the default one; also clears bifurcation_tracking_mode
    virtual std::vector<double> get_parameter_derivative(const std::string param); // d(residuals)/d(param) as a dense vector
    void activate_my_fold_tracking(double *const &parameter_pt, const oomph::DoubleVector &eigenvector, const bool &block_solve); // Starts fold (limit point) bifurcation tracking with a given initial null-eigenvector guess
    void activate_my_fold_tracking(double *const &parameter_pt, const bool &block_solve); // Same, but the eigenvector is determined internally
    void activate_my_pitchfork_tracking(double *const &parameter_pt, const oomph::DoubleVector &eigenvector, const bool &block_solve);
    void activate_my_hopf_tracking(double *const &parameter_pt, const double &omega, const oomph::DoubleVector &null_real, const oomph::DoubleVector &null_imag, const bool &block_solve);
    void activate_my_azimuthal_tracking(double *const &parameter_pt, const double &omega, const oomph::DoubleVector &null_real, const oomph::DoubleVector &null_imag, std::map<std::string, std::string> special_residual_forms);
    void set_arclength_parameter(std::string nam, double val); // Sets the parameter used for arclength continuation (by name) and its current value
    double arc_length_step(const std::string param, const double &ds, unsigned max_adapt); // Performs one pseudo-arclength continuation step in param with step size ds; returns the (possibly adapted) step actually taken
    double get_arc_length_parameter_derivative() { return Parameter_derivative; }
    void set_arc_length_parameter_derivative(double dp) { Parameter_derivative=dp; }
    void set_arc_length_theta_sqr(double thetasqr) {Theta_squared=thetasqr;}
    double get_arc_length_theta_sqr() {return Theta_squared;}
    // Sets up the augmented (bordered) system for tracking a bifurcation of the given typus ("fold","pitchfork","hopf","azimuthal",...)
    // in parameter param, starting from the eigenvector(s) eigenv1/eigenv2 (real/imaginary parts) and, for
    // Hopf-like bifurcations, angular frequency omega.
    void start_bifurcation_tracking(const std::string param, const std::string typus, const bool &blocksolve, const std::vector<double> &eigenv1, const std::vector<double> &eigenv2, const double &omega, std::map<std::string, std::string> special_residual_forms);
    //void start_custom_augmented_system(oomph::AssemblyHandler *handler);
    void reset_augmented_dof_vector_to_nonaugmented(); // Discards any augmentation (bifurcation tracking, arclength, custom) dofs and returns to the plain physical dof vector
    void add_augmented_dofs(DofAugmentations &aug); // Appends the dofs registered in aug to the problem's dof vector
    DofAugmentations * create_dof_augmentation() {return new DofAugmentations(this);}
    void start_orbit_tracking(const std::vector<std::vector<double>> &history, const double &T,int bspline_order,int gl_order,std::vector<double> knots,unsigned T_constraint_mode); // Sets up periodic-orbit tracking from an initial guessed history (time series of dof snapshots) with period T, represented via B-splines
    void after_bifurcation_tracking_step(); // Post-processing hook called after each continuation step while bifurcation tracking is active (e.g. to renormalize the eigenvector)
    double &global_parameter(const std::string &n); // Reference to the value() of the named global parameter (creating it if necessary)

    // Required for custom bifurcation trackers
    oomph::Vector<double *> &GetDofPtr() { return this->Dof_pt; }
    oomph::LinearAlgebraDistribution *GetDofDistributionPt() { return this->Dof_distribution_pt; }
    oomph::Vector<oomph::Vector<unsigned>> &GetSparcseAssembleWithArraysPA() { return this->Sparse_assemble_with_arrays_previous_allocation; }

    virtual void quiet(bool _quiet); // Suppresses/re-enables oomph-lib's and pyoomph's own informational output
    virtual bool _set_solved_residual(std::string name, bool raise_error=true,bool remove_dofs_without_jacobian_row=true); // Switches which named residual (see residual_names) subsequent assembly/solves act on
    bool has_empty_jacobian_rows_marked() const; // Whether the last assemble_defined_field_list()/assign_eqn_numbers() found fields with empty Jacobian rows/cols that had to be pinned
    virtual void _replace_RJM_by_param_deriv(std::string name,bool active); // Toggles replacing the residual/Jacobian/mass-matrix assembly by the derivative w.r.t. parameter name (used internally for parameter-derivative computations)
    virtual std::string _get_solved_residual() { return _solved_residual; }
    virtual bool is_quiet() const { return _is_quiet; }
    // void set_diagonal_zero_entries(bool yesno) {KeepZeroDiagonal=yesno;} //Requires a patched oomph-lib problem class
    Problem();
    virtual void unload_all_dlls(); // Closes all loaded DynamicBulkElementCode shared libraries (called on destruction / explicit cleanup, e.g. before recompiling equations)
    virtual unsigned get_max_dt_order() const; // Maximum time-derivative order required by any of the loaded element codes (determines how many history values the timestepper must keep)
    virtual ~Problem();
    virtual CCompiler *get_ccompiler() { return compiler; }
    virtual void set_ccompiler(CCompiler *comp) { compiler = comp; }
    virtual void assemble_eigenproblem_matrices(oomph::CRDoubleMatrix *&M, oomph::CRDoubleMatrix *&J, double sigma_r); // Assembles the mass matrix M and (shifted) Jacobian J for a generalized eigenvalue problem J*v = sigma*M*v around shift sigma_r

    // Must be overridden (in Python) whenever use_custom_residual_jacobian is set: fills info with
    // user-supplied residuals/Jacobian instead of relying on elemental assembly.
    virtual void  get_custom_residuals_jacobian(CustomResJacInformation * info)
    {
     throw_runtime_error("Must be implemented");
    }

    // Thin wrappers around oomph::Problem's elemental-assembly residual/Jacobian/parameter-derivative
    // routines, kept virtual so that get_residuals/get_jacobian/get_derivative_wrt_global_parameter below
    // can dispatch to either these (normal elemental assembly) or the custom-residual-Jacobian path.
    virtual void get_jacobian_by_elemental_assembly(oomph::DoubleVector &residuals,oomph::CRDoubleMatrix &jacobian)
    {
        oomph::Problem::get_jacobian(residuals,jacobian);
    }
    virtual void get_residuals_by_elemental_assembly(oomph::DoubleVector &residuals)
    {
     oomph::Problem::get_residuals(residuals);
    }
    virtual void get_derivative_wrt_global_parameter_elemental_assembly(double* const& parameter_pt,oomph::DoubleVector &result)
    {
     oomph::Problem::get_derivative_wrt_global_parameter(parameter_pt,result);
    }
    // Top-level entry points for residual/Jacobian/parameter-derivative assembly: dispatch between
    // normal elemental assembly and the custom-residual-Jacobian path (use_custom_residual_jacobian),
    // and additionally apply the matrix-manipulation Dirichlet enforcement when that strategy is active.
    virtual void get_residuals(oomph::DoubleVector &residuals);
    virtual void get_jacobian(oomph::DoubleVector &residuals,oomph::CRDoubleMatrix &jacobian);
    virtual void get_derivative_wrt_global_parameter(double* const& parameter_pt,oomph::DoubleVector& result);
    virtual void remove_dirichlets_by_matrix_manipulation(oomph::DoubleVector &residuals,oomph::CRDoubleMatrix *jacobian=NULL); // Zeroes out rows/columns of Dirichlet-pinned dofs and sets the residual to the constraint violation, in-place on residuals/jacobian

    virtual SparseRank3Tensor assemble_hessian_tensor(bool symmetric); // Assembles the full second-derivative (Hessian) tensor d^2(residual)/d(dof)^2, needed e.g. for bifurcation normal-form/branch-switching computations
    virtual std::vector<double> get_second_order_directional_derivative(std::vector<double> dir); // Directional second derivative of the residuals along dir, computed without forming the full Hessian tensor

    virtual void set_symmetric_hessian_assembly(bool active) {symmetric_hessian_assembly=active;}
    virtual bool get_symmetric_hessian_assembly() const {return symmetric_hessian_assembly;}

    #ifndef OOMPH_HAS_MPI
    virtual void actions_before_distribute() {}
    virtual void actions_after_distribute() {}
    #endif

    void set_FD_step_used_in_get_hessian_vector_products(double step) {FD_step_used_in_get_hessian_vector_products=step;}

    //	 virtual bool _globally_convergent_newton_method() {return Use_globally_convergent_newton_method;} // Damn this private decl
    void open_log_file(const std::string & fname,const bool & activate_logging=true); // Opens fname for logging of solver/Newton diagnostics; pass activate_logging=false to just set the path without starting to log yet

    // Combined assembly of several different requested quantities ("what": residuals, Jacobian, mass
    // matrix, Hessian-vector products, parameter derivatives, ...) restricted to given residual
    // contributions/parameters in a single elemental loop, to avoid redundant element traversals when
    // multiple quantities are needed at once (e.g. by the Python-side continuation/bifurcation code).
    // Results are returned via the output parameters (data/csrdata for dense/sparse pieces, ndof, return_indices).
    void assemble_multiassembly(std::vector<std::string> what,std::vector<std::string> contributions,std::vector<std::string> params,std::vector<std::vector<double>> & hessian_vectors,std::vector<unsigned> & hessian_vector_indices,std::vector<std::vector<double>> & data,std::vector<std::vector<int>> &csrdata,unsigned & ndof,std::vector<int> & return_indices);

  };

  void RequiredShapes_merge(JITFuncSpec_RequiredShapes_FiniteElement_t *src, JITFuncSpec_RequiredShapes_FiniteElement_t *dest); // Merges the "required shapes" flags of src into dest (union of what shape information the elements need)
  void RequiredShapes_free(JITFuncSpec_RequiredShapes_FiniteElement_t *p);
}
