name: PyTest

on:
  workflow_dispatch:

jobs:
  PyTest:
    name: PyTest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        #os: [ubuntu-latest]
        os: [macos-13]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
         python-version: "3.12"

    - name: Install pytest and deps
      run: python -m pip install pyoomph pytest

    - name: Apt install required libs (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt install libglu1-mesa libxcursor1 libopengl0

    - name: Brew install required libs (Mac)
      if: startsWith(matrix.os, 'macos')
      run: brew install gmsh

    - name: Run Self test
      run: cd tests/ && python -m pyoomph check all    
      
    - name: Run PyTest
      run: cd tests/ && python -m pytest *.py
