name: Wheels

# BEFORE RUNNING: Adjust the version in pyoomph/_version.py
# otherwise it will fail at the upload stage
# Also make sure 
#	- Upgrade the CLN and GiNaC versions in citools/compile_win_wheels_msys2.sh AND citools/download_and_build_static_ginac.sh  
#	- Comment the line:     if: github.event_name == 'release' && github.event.action == 'published' 
#		to make the upload work

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15-intel, windows-latest] 

    env:
      CIBW_SKIP: "cp38-* *-manylinux_i686 *-musllinux* *_ppc64le *_s390x *_universal2 *_arm64"  # cp36-* cp37-* pp*

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        if: startsWith(matrix.os, 'windows') != true
        uses: pypa/cibuildwheel@v3.3.1
        

      - uses: msys2/setup-msys2@v2
        if: startsWith(matrix.os, 'windows')
        with:
          msystem: UCRT64
          update: true          # mingw-w64-x86_64-toolchain
          install: >-
            autotools
            patch
            git
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
        

                    
      - shell: msys2 {0}
        if: startsWith(matrix.os, 'windows')
        run: |
           source ./citools/compile_win_wheels_msys2.sh
        

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
            

  upload_all:
    name: Upload if release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: release    
    # if: github.event_name == 'release' && github.event.action == 'published'    

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
